const CACHE_NAME = 'statcannon-pass-20260919-v3';
const CORE_ASSETS = ["./academy/pass/report.js?v=20260919-pass3","./pass/index.html","./academy/pass/engine.js?v=20260919-pass3","./academy/pass/content.js?v=20260919-pass3","./academy/pass/ui.js?v=20260919-pass3","./academy/pass/pass.css?v=20260919-pass3","./academy/hospital-reference.jpg","./academy/studio.css?v=20260918","./academy/medical.css?v=20260919-hospital-deming","./academy/campus.svg","./","./.nojekyll","./academy/academy.css","./academy/app.js?v=20260919-pass3","./academy/content.js","./academy/core.js","./academy/curriculum.js","./academy/extend.js","./academy/learning-loop.js","./academy/legacy.css","./academy/legacy.js?v=20260919-rename","./academy/light.css","./academy/option-feedback-data.js","./academy/option-feedback.js","./academy/practice-queue.js","./academy/question-bank.js","./academy/textbook/corpus.json","./academy/textbook/manifest.json","./academy/textbook-chapters.json","./academy/textbook-engine.js","./academy/textbook-ui.js","./academy/textbook.css","./ai-challenger/index.html","./baizhan_data.js","./baizhan_engine.js","./challenges/index.html","./course/index.html","./datasets/D01/dictionary.json","./datasets/D01/prompt.txt","./datasets/D01/student.csv","./datasets/D01/workbook.md","./datasets/D02/dictionary.json","./datasets/D02/prompt.txt","./datasets/D02/student.csv","./datasets/D02/workbook.md","./datasets/D03/dictionary.json","./datasets/D03/prompt.txt","./datasets/D03/student.csv","./datasets/D03/workbook.md","./datasets/D04/dictionary.json","./datasets/D04/prompt.txt","./datasets/D04/student.csv","./datasets/D04/workbook.md","./datasets/D05/dictionary.json","./datasets/D05/prompt.txt","./datasets/D05/student.csv","./datasets/D05/workbook.md","./datasets/D06/dictionary.json","./datasets/D06/prompt.txt","./datasets/D06/student.csv","./datasets/D06/workbook.md","./datasets/D07/dictionary.json","./datasets/D07/prompt.txt","./datasets/D07/student.csv","./datasets/D07/workbook.md","./datasets/index.html","./datasets/provenance.json","./docs/learning-loop-update.md","./docs/option-feedback-notes.md","./docs/progress-notes.md","./docs/question-bank-notes.md","./docs/question-bank.json","./docs/teaching-guide.md","./docs/textbook-integration.md","./final-boss/index.html","./icon-192.png","./icon-512.png","./index.html","./knowledge.js","./manifest.json","./papers/index.html","./papers/reading-list.md","./reviewer/index.html","./student/index.html","./teacher/index.html","./textbook/index.html"];
self.addEventListener('install', event => event.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(CORE_ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate', event => event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('statcannon-')&&k!==CACHE_NAME).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch', event => {
 const req=event.request;
 if(new URL(req.url).pathname.startsWith('/api/'))return;
 if(req.method!=='GET'||new URL(req.url).origin!==self.location.origin)return;
 event.respondWith(fetch(req).then(resp=>{if(resp.ok){const copy=resp.clone();event.waitUntil(caches.open(CACHE_NAME).then(c=>c.put(req,copy)));}return resp;}).catch(async()=>{
   const cached=await caches.match(req);if(cached)return cached;
   if(req.mode==='navigate')return (await caches.match(new URL('./index.html',self.registration.scope).href))||Response.error();
   return new Response('Offline resource unavailable',{status:503,headers:{'Content-Type':'text/plain'}});
 }));
});
