(() => {
 'use strict';
 const A=window.ACADEMY, C=window.ACADEMY_CORE, KEY='statcannon_academy_v4', base=new URL('.',document.baseURI);
 const routes={student:'首页',textbook:'教材答疑',course:'16学时地图',datasets:'数据实战',challenges:'闯关', 'ai-challenger':'AI打假',reviewer:'审稿人',papers:'论文拆解','final-boss':'Final Boss',teacher:'教师端'};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const defaults=()=>({version:4,learnerId:(crypto.randomUUID ? crypto.randomUUID() : Array.from(crypto.getRandomValues(new Uint8Array(16)), b=>b.toString(16).padStart(2,'0')).join('')),xp:0,streak:0,best:0,awarded:[],attempts:[],completed:[],notes:{},paperNotes:{},boss:{},diagnostics:[],teacherReports:[],lesson:1,curriculum:'v3-119',lessonResults:{}});
 let progress=defaults(),storageOK=true,quiz=null;
 try{const old=JSON.parse(localStorage.getItem(KEY)||'null');if(C.validProgress(old))progress={...progress,...old,teacherReports:Array.isArray(old.teacherReports)?old.teacherReports:[]};}catch(e){storageOK=false;}
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(progress));}catch(e){storageOK=false;showToast('无法保存到浏览器，请导出学习档案备份。');}};
 const root=document.createElement('section');root.id='page-academy';root.className='page';document.getElementById('main').prepend(root);
 const nav=document.createElement('nav');nav.id='academy-nav';nav.setAttribute('aria-label','课程平台');document.getElementById('top-bar').after(nav);
 const url=path=>new URL(path,base).href;
 const link=(route,text,cls='ac-btn')=>`<a class="${cls}" data-route="${route}" href="${url(route+'/')}">${esc(text)}</a>`;
 const button=(action,text,extra='',cls='ac-btn')=>`<button class="${cls}" data-action="${action}" ${extra}>${esc(text)}</button>`;
 nav.innerHTML=Object.entries(routes).map(([k,v])=>link(k,v,'')).join('');
 const quick=document.createElement('div');quick.className='sc-quick';quick.innerHTML='<span>学习工具</span>';quick.append(document.getElementById('top-nav'));nav.append(quick);
 const hospitalCorner=document.createElement('div');hospitalCorner.className='sc-hospital-corner';hospitalCorner.innerHTML='<img src="academy/hospital-reference.jpg" alt="北京大学深圳医院院景：用统计的力量，让医学研究更有证据">';nav.append(hospitalCorner);
 const oldSwitch=window.switchPage;
 window.switchPage=function(name){oldSwitch(name);nav.querySelectorAll('a').forEach(a=>a.removeAttribute('aria-current'));history.replaceState({},'',url('')+'#legacy-'+name);};
 const oldRecord=window.recordAnswer;
 window.recordAnswer=function(q,correct,...rest){oldRecord(q,correct,...rest);const topic=q.topicId||rest[2];const m=A.lessons.find(l=>l.topic===topic);record(q.qid||q.q,q.q,correct,m?.skill??2,'cannon',q.explain||'',topic,q);};
 function record(id,text,correct,skill,mode,explain,topic,question){
   progress.streak=correct?progress.streak+1:0;progress.best=Math.max(progress.best,progress.streak);
   if(correct&&!progress.awarded.includes(id)){progress.xp+=20;progress.awarded.push(id);}
   progress.attempts.push({id,text,correct,skill,mode,explain,topic,...(question?{options:[...question.options],answer:question.answer,selectedOption:question.selectedOption}:{}),ts:new Date().toISOString()});save();
 }
 function scores(){return A.skills.map((_,i)=>{const latest=new Map();progress.attempts.filter(a=>a.skill===i).forEach(a=>latest.set(a.id,a));const values=[...latest.values()];return {n:values.length,value:values.length?Math.round(100*values.filter(a=>a.correct).length/values.length):null};});}
 function radar(){const s=scores(),pt=(i,r)=>[170+Math.sin(i*Math.PI/3)*r,160-Math.cos(i*Math.PI/3)*r],poly=r=>A.skills.map((_,i)=>pt(i,r).join(',')).join(' ');return `<svg class="ac-radar" viewBox="0 0 340 325" role="img" aria-label="六维统计能力雷达，未测维度按0绘图，详情见下方列表">${[35,70,105].map(r=>`<polygon points="${poly(r)}" fill="none" stroke="#465674"/>`).join('')}${A.skills.map((_,i)=>`<line x1="170" y1="160" x2="${pt(i,105)[0]}" y2="${pt(i,105)[1]}" stroke="#465674"/>`).join('')}<polygon points="${s.map((v,i)=>pt(i,(v.value||0)*1.05).join(',')).join(' ')}" fill="#fbbf2433" stroke="#fbbf24" stroke-width="2"/>${A.skills.map((x,i)=>`<text x="${pt(i,138)[0]}" y="${pt(i,138)[1]+5}" text-anchor="middle">${x}</text>`).join('')}</svg><div class="ac-row">${s.map((v,i)=>`<span class="ac-tag">${A.skills[i]} ${v.value===null?'未测':v.value+'%'} · ${v.n}题</span>`).join('')}</div>`;}
 function stats(){return `<div class="ac-row"><div class="ac-stat"><b>${progress.xp}</b><span>XP · 每题首次答对+20</span></div><div class="ac-stat"><b>Lv.${1+Math.floor(progress.xp/200)}</b><span>每200 XP升级</span></div><div class="ac-stat"><b>${progress.best}</b><span>最高连续答对</span></div><div class="ac-stat"><b>${progress.completed.length}/16</b><span>自评完成学时</span></div></div>`;}
 function lessonTiles(){return A.lessons.map(l=>`<button class="ac-lesson ${progress.completed.includes(l.id)?'done':''}" data-action="lesson" data-id="${l.id}"><span class="ac-num">${String(l.id).padStart(2,'0')}</span> <small>${progress.completed.includes(l.id)?'✓ 已自评完成':l.dataset+' · 45分钟'}</small><strong>${l.title}</strong><small>${A.skills[l.skill]}</small></button>`).join('');}
 function studioIcon(type){const paths={book:'M12 5C8 2 4 2 2 3v16c4-1 7 0 10 2 3-2 6-3 10-2V3c-2-1-6-1-10 2Zm0 0v16',target:'M20 11a8 8 0 1 1-7-7M12 8a4 4 0 1 0 4 4M12 12l9-9m-5 0h5v5',bars:'M4 20V12h3v8M10 20V7h3v13M16 20V3h3v17M2 23h20',folder:'M2 7V4h7l3 3h10v14H2V7Zm0 3h20',chart:'M4 20V13m7 7V8m7 12V3',chat:'M4 4h16v13H9l-5 4V4Zm4 5h8m-8 4h5',check:'m5 12 4 4L19 6'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${(paths[type]||paths.book).split('ZZ').map(d=>`<path d="${d}"/>`).join('')}</svg>`;}
 function student(){
  const allTopics=KNOWLEDGE_TREE.flatMap(m=>m.topics),values=allTopics.map(t=>getTopicMastery(t.id));
  const groups=[{label:'优秀 ≥85%',n:values.filter(v=>v!==null&&v>=85).length,color:'#20b894'},{label:'待巩固 60–84%',n:values.filter(v=>v!==null&&v>=60&&v<85).length,color:'#f6bd43'},{label:'薄弱 <60%',n:values.filter(v=>v!==null&&v<60).length,color:'#ee7771'},{label:'未测试',n:values.filter(v=>v===null).length,color:'#e7eff5'}];
  let angle=0;const ring=groups.map(g=>{const from=angle;angle+=g.n/allTopics.length*100;return `${g.color} ${from}% ${angle}%`}).join(',');
  const tested=values.filter(v=>v!==null).length,pct=Math.round(tested/allTopics.length*100),current=A.lessons.find(l=>!progress.completed.includes(l.id))||A.lessons[15];
  const features=[
   {type:'book',tone:'blue',title:'统计基础与知识树',desc:'系统学习卫生统计学知识，构建完整知识体系。',items:['知识树导航','核心概念解析','五环节学习'],action:'legacy-learn',cta:'进入知识树'},
   {type:'target',tone:'green',title:'统计闯关测试',desc:'在答题中训练统计判断，巩固提升、逐题进阶。',items:['多种题型训练','即时评分解析','错题强化练习'],action:'legacy-cannon',cta:'开始统计闯关'},
   {type:'bars',tone:'orange',title:'16学时科研课堂',desc:'沿着临床研究主线，把统计方法用到真实问题中。',items:['研究设计与推断','回归与生存分析','论文拆解与答辩'],route:'course',cta:'查看课程地图'},
   {type:'folder',tone:'purple',title:'D01–D07 教学案例库',desc:'七套模拟研究数据，从临床问题到统计分析。',items:['配套CSV与变量字典','研究情境与任务单','AI代码练习提示'],route:'datasets',cta:'进入数据实战'},
   {type:'chart',tone:'teal',title:'进度与掌握度分析',desc:'看见学习轨迹，定位薄弱环节，安排下一步。',items:['知识点掌握度','个性化补弱方案','学习档案与备份'],action:'legacy-weakness',cta:'查看薄弱点'},
   {type:'chat',tone:'sky',title:'教材答疑与反馈',desc:'检索内置教材，结合原文理解统计概念与方法。',items:['教材知识检索','原文依据追溯','统计问题学习建议'],route:'textbook',cta:'向教材提问'}
  ];
  const cards=features.map(f=>`<article class="sc-feature ${f.tone}"><div class="sc-feature-icon">${studioIcon(f.type)}</div><h2>${f.title}</h2><p>${f.desc}</p><ul>${f.items.map(x=>`<li>${studioIcon('check')}<span>${x}</span></li>`).join('')}</ul>${f.route?link(f.route,f.cta,'sc-feature-go'):button(f.action,'↗',`aria-label="${f.cta}"`,'sc-feature-go')}<span class="sc-sr">${f.cta}</span></article>`).join('');
  const recent=[...progress.attempts].reverse().slice(0,4);
  return `<section class="sc-med-hero"><div class="sc-med-hero-copy"><div class="ac-eyebrow">STATCANNON · MEDICAL STATISTICS</div><h1>统计学大炮</h1><h2>卫生统计学学习、案例训练与科研教学平台</h2><p>以数据认识世界 · 用统计推动医学 · 从学习走向科研</p></div><div class="sc-hero-motto">好的医学研究<br><span>从正确的统计开始</span></div><div class="sc-hospital-photo" role="img" aria-label="用户提供的北京大学深圳医院建筑参考图"><img src="academy/hospital-reference.jpg" alt=""></div></section>
  <section class="sc-feature-grid" aria-label="学习功能">${cards}</section>
  <section class="sc-dashboard" aria-label="学习概览"><article class="ac-card sc-overview"><div class="sc-panel-title"><h2>学习进度总览</h2>${link('course','查看课程 →','sc-more')}</div><div class="sc-overview-body"><div class="sc-ring" style="--ring:conic-gradient(#2aa9ed ${pct}%,#e7eff5 0)" role="img" aria-label="已测试知识点覆盖率 ${pct}%"><div><strong>${pct}%</strong><small>知识点覆盖率</small></div></div><dl><div><dt>已测试知识点</dt><dd>${tested}<small> / ${allTopics.length}</small></dd></div><div><dt>自评完成学时</dt><dd>${progress.completed.length}<small> / 16</small></dd></div><div><dt>课堂答题记录</dt><dd>${progress.attempts.length}<small> 次</small></dd></div><div><dt>累计学习经验</dt><dd>${progress.xp}<small> XP</small></dd></div></dl></div><p class="sc-panel-note">覆盖率按已作答知识点计算，不代表已掌握。</p></article>
  <article class="ac-card sc-mastery"><div class="sc-panel-title"><h2>知识点掌握度</h2>${button('legacy-weakness','查看详情 →','','sc-more')}</div><div class="sc-overview-body"><div class="sc-ring" style="--ring:conic-gradient(${ring})" role="img" aria-label="知识点总数 ${allTopics.length}，${groups.map(g=>g.label+g.n+'个').join('，')}"><div><strong>${allTopics.length}</strong><small>知识点总数</small></div></div><ul class="sc-legend">${groups.map(g=>`<li><i style="background:${g.color}"></i><span>${g.label}</span><b>${g.n}</b></li>`).join('')}</ul></div><p class="sc-panel-note">按知识点累计正确率统计 · 灰色为未测试</p></article>
  <article class="ac-card sc-activity"><div class="sc-panel-title"><h2>最近学习动态</h2>${button('errors','错题记录 →','','sc-more')}</div>${recent.length?`<ul>${recent.map(a=>`<li><span class="sc-activity-dot ${a.correct?'is-correct':''}">${a.correct?'✓':'↻'}</span><div><strong>${esc(a.text)}</strong><small>${a.correct?'回答正确':'待复习'} · ${esc(new Date(a.ts).toLocaleDateString('zh-CN'))}</small></div></li>`).join('')}</ul>`:`<div class="sc-empty-activity">${studioIcon('book')}<strong>让第一道题，开启学习轨迹</strong><p>完成课堂诊断或练习后，学习记录会显示在这里。</p>${button('diagnostic','开始课前诊断 · 12题','','ac-btn primary')}</div>`}</article></section>
  <section class="sc-bottom"><figure class="sc-deming"><div class="sc-deming-portrait"><img src="academy/hospital-reference.jpg" alt="W. Edwards Deming（戴明）肖像，取自用户提供的模板"></div><figcaption><blockquote>“没有数据，就只是一种意见。”</blockquote><p>— W. Edwards Deming（戴明）</p></figcaption></figure><article class="sc-continue"><span class="sc-next-label">继续学习 · 第 ${current.id} 学时</span><h2>${current.title}</h2>${button('lesson','进入本学时 →',`data-id="${current.id}"`,'sc-more')}</article><article class="sc-philosophy"><span>更好的临床研究，从掌握统计开始</span><small>BETTER DATA. BETTER MEDICINE.</small></article></section>
  <section class="sc-archive"><div><strong>我的学习档案</strong><span>当前浏览器保存 · 更换设备前请导出备份</span></div><div class="ac-row">${button('export','导出档案')}${button('import','导入档案')}${button('diagnostic','统计能力诊断')}</div></section>`;
 }
 function course(){return `<div class="ac-eyebrow">CAMPAIGN / 16 × 45 MIN</div><h1>16学时，一条科研主线</h1><p class="ac-muted">每学时45分钟，共720分钟；可合并为8次双学时课。建议：问题与首判5分钟、理论10分钟、数据实战15分钟、纠错与论文10分钟、补弱与退出测验5分钟。</p><div class="ac-track">${lessonTiles()}</div>`;}
 function lesson(id){const l=A.lessons.find(l=>l.id===id);if(!l)return;progress.lesson=id;save();show('course',false);root.innerHTML=`<div class="ac-eyebrow">MISSION ${String(id).padStart(2,'0')} / ${l.dataset} / PPT ${l.pages}页 / 45分钟</div><h1>${l.title}</h1><div class="ac-card"><h2>01 · 临床 / 科研问题</h2><p>${l.question}</p>${button('topic','先开炮，做出首次判断',`data-topic="${l.topic}"`,'ac-btn primary')}</div><div class="ac-card"><h2>02 · 理论学习</h2><p>${l.theory}</p>${button('theory','打开原版知识卡',`data-topic="${l.topic}"`)} <a class="ac-btn" href="${url('textbook/')}?q=${encodeURIComponent(l.title+'的主要概念与适用条件是什么？')}">向教材提问</a></div><div class="ac-card"><h2>03 · 数据实战</h2><p>${l.deliverable}</p><div class="ac-row">${button('dataset','打开'+l.dataset+'数据实验室',`data-id="${l.dataset}"`)}<a class="ac-btn" href="${url('datasets/'+l.dataset+'/student.csv')}" download>下载CSV</a></div></div><div class="ac-card"><h2>04 · AI辅助与反驳</h2><p>使用数据库配套Prompt生成分析代码，自己运行并记录差异。这里的AI挑战是预编写的错误案例，不会调用外部模型。</p><div class="ac-row">${link('ai-challenger','AI统计打假')}${link('reviewer','进入审稿人模式')}</div></div><div class="ac-card"><h2>05 · 退出测验与反思</h2>${button('lesson-quiz','本学时退出测验',`data-id="${id}"`,'ac-btn primary')}<p class="ac-muted">${progress.lessonResults?.[id]?`最近测验：${progress.lessonResults[id].correct}/${progress.lessonResults[id].total}。`:'尚未完成本学时测验。'}测验与自评完成分别记录。</p>${link('papers','阅读真实论文拆解卡')}<label for="lesson-note">本学时提交：判断、代码/结果摘要、纠错依据与下一步</label><textarea id="lesson-note" placeholder="记录你的答案与反思，先保存再离开页面。">${esc(progress.notes[id]||'')}</textarea><div class="ac-row">${button('save-note','保存学习记录',`data-id="${id}"`)}${button('complete-lesson',progress.completed.includes(id)?'已自评完成':'记录完成并返回地图',`data-id="${id}"`,'ac-btn primary')}</div><p class="ac-muted">完成标记是学生自评，不代表教师评分或客观通过。</p></div>`;}
 function datasetList(){return `<div class="ac-eyebrow">DATA LAB / SYNTHETIC ONLY</div><h1>七座数据靶场</h1><p class="ac-muted">全部沿用V3课程包中的模拟数据，刻意保留教学问题。每套提供学生CSV、变量字典、AI Prompt与课堂任务单；不能作为真实研究证据。</p><div class="ac-grid">${A.datasets.map(d=>`<article class="ac-card"><span class="ac-eyebrow">${d.id} / ${d.n}行</span><h2>${d.title}</h2><p>${d.method}</p><p class="ac-muted">${d.traps}</p><div class="ac-row">${button('dataset','进入实验室',`data-id="${d.id}"`,'ac-btn primary')}</div></article>`).join('')}</div>`;}
 async function dataset(id){const d=A.datasets.find(x=>x.id===id);if(!d)return;show('datasets',false);root.innerHTML=`<h1>${id} · ${d.title}</h1><p>正在读取数据与字典…</p>`;try{const [csv,dict,prompt]=await Promise.all(['student.csv','dictionary.json','prompt.txt'].map(async name=>{const r=await fetch(url(`datasets/${id}/${name}`));if(!r.ok)throw Error('HTTP '+r.status);return r.text();}));if(!root.textContent.includes(id+' ·'))return;const dd=JSON.parse(dict),rows=C.parseCSV(csv);const cols=rows[0],data=rows.slice(1);root.innerHTML=`<div class="ac-eyebrow">${id} / 模拟数据 / ${data.length}行</div><h1>${d.title}</h1><p>${esc(dd.description)}</p><div class="ac-row"><a class="ac-btn primary" download href="${url(`datasets/${id}/student.csv`)}">下载学生CSV</a><a class="ac-btn" download href="${url(`datasets/${id}/dictionary.json`)}">变量字典</a><a class="ac-btn" download href="${url(`datasets/${id}/prompt.txt`)}">AI Prompt</a></div><p><a class="ac-btn" href="${url(`datasets/${id}/workbook.md`)}" target="_blank">打开课堂任务单</a></p><h2 class="ac-section">数据预览 · 前8行</h2><div class="ac-table-wrap"><table class="ac-table"><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${data.slice(0,8).map(row=>`<tr>${row.map(v=>`<td>${v===''?'缺失':esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="ac-two"><div class="ac-card"><h2>先判断，再检查</h2><label for="lab-column">选择变量</label><select id="lab-column">${cols.slice(1).map(c=>`<option>${esc(c)}</option>`).join('')}</select><div class="ac-row" style="margin-top:12px">${button('audit','检查缺失与重复ID')}${button('summary','计算变量描述')}</div><div id="lab-output" class="ac-feedback" role="status" style="margin-top:16px"></div><p class="ac-muted">浏览器只做数据审查和描述。回归、生存分析与插补请下载数据，在R中运行配套脚本。</p></div><div class="ac-card"><h2>变量字典</h2>${Object.entries(dd.fields).map(([k,v])=>`<p><strong>${esc(k)}</strong>：${esc(v)}</p>`).join('')}</div></div><details><summary>展开AI实战Prompt</summary><pre>${esc(prompt)}</pre></details>`;root._data={cols,data};}catch(e){root.innerHTML=`<h1>${id}读取失败</h1><p>请检查网络；离线时需先在线打开此数据集一次。</p>${button('dataset','重试',`data-id="${id}"`)}`;}}
 function audit(summary=false){const {cols,data}=root._data,el=document.getElementById('lab-output');if(!summary){const duplicate=data.length-new Set(data.map(r=>r[0])).size;el.innerHTML=`<p>总行数 ${data.length}；重复ID行数 ${duplicate}。</p>${cols.map((c,i)=>`<p>${esc(c)}：缺失 ${data.filter(r=>r[i]==='').length}</p>`).join('')}`;}else{const col=document.getElementById('lab-column').value,idx=cols.indexOf(col),valid=data.map(r=>r[idx]).filter(v=>v!==''),nums=valid.map(Number);if(nums.some(x=>!Number.isFinite(x))){const counts={};valid.forEach(v=>counts[v]=(counts[v]||0)+1);el.textContent=col+'：'+JSON.stringify(counts);return;}nums.sort((a,b)=>a-b);if(!nums.length){el.textContent='没有可用数值。';return;}const n=nums.length,mean=nums.reduce((a,b)=>a+b,0)/n,sd=n>1?Math.sqrt(nums.reduce((s,x)=>s+(x-mean)**2,0)/(n-1)):NaN,q=p=>{const pos=(n-1)*p,a=Math.floor(pos);return nums[a]+(nums[Math.min(a+1,n-1)]-nums[a])*(pos-a);};el.innerHTML=`<p>${esc(col)} · 有效n=${n}，缺失=${data.length-n}</p><p>均值 ${mean.toFixed(2)} · SD ${Number.isNaN(sd)?'不适用':sd.toFixed(2)}</p><p>中位数 ${q(.5).toFixed(2)} · Q1 ${q(.25).toFixed(2)} · Q3 ${q(.75).toFixed(2)}</p><p>范围 ${nums[0]}–${nums[n-1]}</p><p>以上包含未经清洗的数值与重复记录；数值编码的分类变量应按类别解释。</p>`;}}
 function challenges(){const topicIDs=['t8','t10','t12','t13','t14','t42','t33','t43'];return `<div class="ac-eyebrow">CANNON CAMPAIGN / METHOD GATES</div><h1>选择你的统计战场</h1><p class="ac-muted">这些关卡直接使用原版大炮引擎。作答同时更新XP、错题档案与个人雷达。</p><div class="ac-grid">${topicIDs.map(t=>{const x=KNOWLEDGE_TREE.flatMap(m=>m.topics).find(x=>x.id===t);return `<article class="ac-card"><h2>${esc(x.name)}</h2><p class="ac-muted">${esc(x.summary||'判断方法适用场景、假设与结果解释。')}</p>${button('topic','瞄准 · 开炮',`data-topic="${t}"`,'ac-btn primary')}</article>`;}).join('')}</div>`;}
 function papers(){return `<div class="ac-eyebrow">EVIDENCE / PRIMARY PUBLICATIONS</div><h1>把方法放回真实论文</h1><p>与V3课件一致：8篇研究论文、3项报告规范。</p><p class="ac-muted">链接指向原始论文；下列为原创教学拆解，不是全文转载。模拟数据不来自这些试验。</p>${A.papers.map(p=>`<article class="ac-card"><span class="ac-tag">${p.journal}</span><h2>${p.title}</h2><p>${p.design} · ${p.focus}</p><a class="ac-btn" href="${p.url}" target="_blank" rel="noopener noreferrer">阅读原文 · DOI ${p.doi}</a><ol class="ac-list">${p.tasks.map(t=>`<li>${t}</li>`).join('')}</ol><label for="paper-${p.id}">你的拆解（写出原文表号/段落，区分事实与推断）</label><textarea id="paper-${p.id}">${esc(progress.paperNotes[p.id]||'')}</textarea>${button('save-paper','保存拆解',`data-id="${p.id}"`)}<details><summary>完成后核对教学要点</summary><p>${p.answer}</p></details></article>`).join('')}`;}
 function modePage(mode){const ai=mode==='ai';return `<div class="ac-eyebrow">${ai?'AI CHALLENGER':'REVIEWER MODE'} / ${A.questions.filter(q=>q.mode===mode).length} CHALLENGES</div><h1>${ai?'AI很自信，你要更严谨。':'这篇论文，你会放行吗？'}</h1><div class="ac-command"><h2>${ai?'击穿流畅答案里的统计漏洞':'从结果表述追到方法与证据'}</h2><p>${ai?'识别错误假设、配对结构丢失、混杂筛选、PH违背与数据泄漏。':'每条审稿意见都应指出问题、解释后果，并给出可执行修改。'}</p><p class="ac-muted">预编写教学案例，即时解析；无需API，不自动生成或代替正式审稿。</p>${button('quiz','进入挑战',`data-mode="${mode}"`,'ac-btn primary')}</div>`;}
 function legacyQuestions(topic){return getAllQuestions().filter(q=>!topic||q.topicId===topic).map(q=>({...q,id:q.qid||q.q,topic:q.topicId,skill:A.lessons.find(l=>l.topic===q.topicId)?.skill??2}));}
 function startQuiz(mode,lessonId){
  let items=[];
  if(mode==='lesson'){const l=A.lessons.find(x=>x.id===lessonId);items=C.shuffled(legacyQuestions(l.topic)).slice(0,3).map(q=>({...q,skill:l.skill}));}
  else if(mode==='retry'){const latest=new Map();progress.attempts.forEach(a=>latest.set(a.id,a));const pool=[...A.questions,...legacyQuestions()];items=C.shuffled(pool.filter(q=>latest.get(q.id)?.correct===false));}
  else items=C.shuffled(A.questions.filter(q=>q.mode===mode));
  if(!items.length){showToast('当前没有可复测题目，请先完成一次练习。');return;}
  quiz={mode,lessonId,items,i:0,results:[],answered:false};show(mode==='ai'?'ai-challenger':mode==='reviewer'?'reviewer':'student',false);renderQuiz();
 }
 function renderQuiz(){if(quiz.i>=quiz.items.length){const n=quiz.results.filter(Boolean).length;if(quiz.mode==='lesson'){progress.lessonResults=progress.lessonResults||{};progress.lessonResults[quiz.lessonId]={correct:n,total:quiz.items.length,ts:new Date().toISOString()};save();}if(quiz.mode==='diagnostic'){progress.diagnostics.push({ts:new Date().toISOString(),correct:n,total:quiz.items.length,answers:quiz.results});save();}root.innerHTML=`<div class="ac-command"><div class="ac-eyebrow">MISSION COMPLETE</div><h1>${n} / ${quiz.items.length} 命中</h1><p>每道题首次答对获得20 XP；重复作答用于补弱，不重复刷分。</p>${stats()}</div><div class="ac-two"><div class="ac-card"><h2>更新后的能力地图</h2>${radar()}</div><div class="ac-card"><h2>下一步</h2>${quiz.lessonId?button('lesson','返回本学时',`data-id="${quiz.lessonId}"`):''}<p>回看错误依据，进入对应知识点练习，再用数据库验证。</p><div class="ac-row">${button('errors','查看错题')}${link('datasets','去数据实战')}${link('student','返回作战大厅')}</div></div></div>`;return;}const q=quiz.items[quiz.i];quiz.answered=false;root.innerHTML=`<div class="ac-row ac-between"><span class="ac-eyebrow">${quiz.mode==='diagnostic'?'课前 / 课后诊断':quiz.mode==='ai'?'AI统计打假':quiz.mode==='lesson'?'本学时退出测验':quiz.mode==='retry'?'错题复测':'审稿人挑战'} · ${quiz.i+1}/${quiz.items.length}</span><span class="ac-tag">${A.skills[q.skill]}</span></div><div class="ac-meter"><div style="width:${100*quiz.i/quiz.items.length}%"></div></div><div class="ac-card" id="quiz-arena"><h1 style="font-size:25px">${q.q}</h1><div class="ac-options">${q.options.map((o,i)=>`<button class="ac-option" data-action="answer" data-choice="${i}"><b>${'ABCD'[i]}</b><span>${esc(o)}</span></button>`).join('')}</div><div class="ac-feedback" id="quiz-feedback" role="status"></div><div class="ac-row">${button('next-question','下一题','disabled','ac-btn primary')}${link('student','退出挑战')}</div></div>`;}
 function answer(choice){if(!quiz||quiz.answered)return;quiz.answered=true;const q=quiz.items[quiz.i],ok=choice===q.answer;quiz.results.push(ok);q.selectedOption=q.options[choice];record(q.id,q.q,ok,q.skill,quiz.mode,q.explain,q.topic,q);root.querySelectorAll('.ac-option').forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add('correct');else if(i===choice)b.classList.add('wrong');});document.getElementById('quiz-feedback').innerHTML='<p><strong>'+(ok?'命中！':'本次未命中。')+'</strong></p>'+window.STATCANNON_FEEDBACK.render(q,choice);document.getElementById('quiz-arena').classList.add('ac-shot');root.querySelector('[data-action=next-question]').disabled=false;}
 function errors(){
  const latest=new Map();progress.attempts.forEach(a=>latest.set(a.id,a));const wrong=[...latest.values()].filter(a=>!a.correct);
  const pool=[...A.questions,...legacyQuestions()];
  root.innerHTML=`<h1>错题档案 · ${wrong.length}道待复习</h1>${wrong.length?button('retry','开始错题复测','','ac-btn primary'):''}<p class="ac-muted">展示每道题最近一次仍答错的记录，逐项核对概念与适用条件。</p>${wrong.length?wrong.map(a=>{
   const original=pool.find(q=>q.id===a.id)||pool.find(q=>q.q===a.text);
   const snapshot=Array.isArray(a.options)&&original&&a.options.length===original.options.length&&a.options.every(o=>original.options.includes(o));
   const q=original?{...original,...(snapshot?{options:a.options,answer:a.options.indexOf(original.options[original.answer])}:{})}:null;
   const selected=q?.options.indexOf(a.selectedOption)??-1;
   return `<article class="ac-card"><span class="ac-tag">${A.skills[a.skill]}</span><h2>${esc(a.text)}</h2>${q?window.STATCANNON_FEEDBACK.render(q,selected,{historical:true}):`<p>${esc(a.explain||'请回到对应知识卡查看解析。')}</p>`}${a.topic?button('theory','学习对应知识点',`data-topic="${esc(a.topic)}"`):''}</article>`;
  }).join(''):'<p class="ac-empty">暂无待复习错题；若尚未作答，请先完成能力诊断。</p>'}`;
 }

 const rubric=[['研究问题与分析计划',15,'明确人群、主要结局、估计目标与分析集。'],['数据清洗与缺失',20,'提供字典、清洗日志、缺失机制讨论与敏感性方案。'],['模型选择与诊断',25,'调整混杂、检查函数形式/残差/PH，避免机械筛选。'],['效应与稳健性',20,'报告效应量、95%CI、验证和敏感性结果，区分主要/探索分析。'],['报告与复现',20,'交付可运行代码、环境信息、表图、AI核查记录和局限。']];
 function boss(){return `<div class="ac-eyebrow">FINAL BOSS / D01—D07</div><h1>交付一份站得住的医学分析</h1><div class="ac-command"><h2>自主选择一个课程项目</h2><p>沿用D01—D07原始数据。请在分析计划首行注明数据编号；先锁定主要问题，再运行分析。项目课前完成，第16学时按8分钟汇报、4分钟追问组织。</p>${link('datasets','选择数据项目','ac-btn primary')}</div><div class="ac-two"><div class="ac-card"><h2>提交区</h2>${['analysisPlan','methods','results','limitations','aiAudit'].map((k,i)=>`<label for="boss-${k}">${['预设分析计划与主要结局','清洗与模型方法（可粘贴R代码）','效应量、区间与敏感性结果','局限与下一步','AI使用及人工核验记录'][i]}</label><textarea id="boss-${k}">${esc(progress.boss[k]||'')}</textarea>`).join('')}<div class="ac-row">${button('save-boss','保存草稿')}${button('submit-boss','生成提交文件','','ac-btn primary')}</div><p class="ac-muted">生成文件后交给教师；此页面不会自动上传到班级，也不会用字数代替学术评分。</p></div><div class="ac-card"><h2>教师评分量表 · 100分</h2>${rubric.map(([n,s,t])=>`<h3>${n} · ${s}分</h3><p>${t}</p>`).join('')}</div></div>`;}
 function teacher(){return `<div class="ac-eyebrow">INSTRUCTOR / CLASSROOM MODE</div><h1>把游戏串成一堂课</h1><p class="ac-muted">教师视图是公开的教学工具，未设置账号或答案保密。当前支持本机课堂控制与手工导入学生学习档案，不是多人实时后台。</p><div class="ac-two"><div class="ac-card"><h2>课堂控制台</h2><label for="teacher-lesson">选择本学时</label><select id="teacher-lesson">${A.lessons.map(l=>`<option value="${l.id}" ${progress.lesson===l.id?'selected':''}>${l.id}. ${l.title}</option>`).join('')}</select><div class="ac-row" style="margin-top:15px">${button('teach','打开本学时教学流程','','ac-btn primary')}${button('diagnostic','全班课前测验')}</div><h3 class="ac-section">45分钟节奏</h3><p>问题首判5 → 理论10 → 数据15 → 纠错/论文10 → 补弱5分钟。</p><label for="timer-minutes">计时分钟数</label><input id="timer-minutes" type="number" min="1" max="120" value="5"><div class="ac-row" style="margin-top:10px">${button('timer','开始 / 重置计时')}${button('stop-timer','停止')}<strong id="timer-output" role="timer">未开始</strong></div></div><div class="ac-card"><h2>班级档案汇总</h2><p>学生导出学习档案后，教师在此导入多个JSON文件。汇总仅保存在当前浏览器。</p>${button('teacher-import','导入学生档案')}<div id="teacher-summary">${teacherSummary()}</div></div></div><h2 class="ac-section">授课配套</h2><p>教师答案保留在离线源码包中，不随学生网页发布。此处的课堂控制与汇总仅在当前浏览器生效。</p><a class="ac-btn" href="${url('docs/teaching-guide.md')}" target="_blank">授课执行与方法学补充</a>`;}
 function teacherSummary(){const reports=progress.teacherReports;if(!reports.length)return '<p class="ac-empty">尚未导入学生档案。</p>';return `<p>已导入 ${reports.length}份档案（同一档案编号保留较新记录；旧版无编号档案单独保留）。</p><div class="ac-table-wrap"><table class="ac-table"><tr><th>档案名</th><th>XP</th><th>自评学时</th><th>最近诊断</th></tr>${reports.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.xp)}</td><td>${esc(r.completed)}/16</td><td>${esc(r.diagnostic)}</td></tr>`).join('')}</table></div>`;}
 function download(name,value){const blob=new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type:'application/json;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 const validProgress=C.validProgress;
 function importFiles(teacherMode){const input=document.createElement('input');input.type='file';input.accept='.json';input.multiple=teacherMode;input.onchange=async()=>{let loaded=0;for(const file of input.files){try{if(file.size>5e6)throw Error('文件超过5MB');const raw=JSON.parse(await file.text());const p=raw.progress;if(raw.format!=='statcannon-academy'||!validProgress(p))throw Error('不是有效的StatCannon学习档案');if(teacherMode){const dx=p.diagnostics.at(-1);const record={learnerId:p.learnerId||null,exportedAt:Number.isFinite(Date.parse(raw.exportedAt))?raw.exportedAt:new Date().toISOString(),name:file.name,xp:p.xp,completed:p.completed.length,diagnostic:dx?`${dx.correct}/${dx.total}`:'未测'};progress.teacherReports=C.mergeReport(progress.teacherReports,record);}else{if(!confirm('导入将替换本机课程进度。是否继续？'))return;progress={...defaults(),...p,teacherReports:progress.teacherReports,lessonResults:p.lessonResults||{}};}loaded++;}catch(e){showToast(file.name+'：'+e.message);}}save();show(teacherMode?'teacher':'student',false);if(loaded)showToast('成功导入'+loaded+'份档案');};input.click();}
 let timer=null;
 function show(route,change=true){if(state.gameActive)endCannonGame();if(!routes[route])route='student';document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));root.classList.add('active');document.querySelectorAll('#top-nav button').forEach(b=>b.classList.remove('active'));nav.querySelectorAll('a').forEach(a=>{a.removeAttribute('aria-current');if(a.dataset.route===route)a.setAttribute('aria-current','page');});if(change)history.pushState({},'',url(route+'/'));const views={student,textbook:()=>window.TextbookQA.shell(),course,datasets:datasetList,challenges,'ai-challenger':()=>modePage('ai'),reviewer:()=>modePage('reviewer'),papers,'final-boss':boss,teacher};root.innerHTML=views[route]()+`<footer class="ac-footer">StatCannon · 徐俊杰老师原版游戏 / 课程扩展 v${A.version} · 模拟数据教学 · ${storageOK?'当前浏览器本地保存':'保存不可用，请导出备份'}</footer>`;if(route==='textbook')window.TextbookQA.mount(root);window.scrollTo({top:0,behavior:'instant'});}
 function routeFromLocation(){if(location.hash.startsWith('#legacy-')){oldSwitch(location.hash.slice(8));return;}const path=location.pathname.slice(base.pathname.length).split('/')[0];show(routes[path]?path:'student',false);}
 document.addEventListener('click',e=>{const a=e.target.closest('[data-route]');if(a){e.preventDefault();quiz=null;show(a.dataset.route);return;}const b=e.target.closest('[data-action]');if(!b)return;const d=b.dataset;switch(d.action){
   case'lesson':lesson(Number(d.id));break;
   case'legacy-cannon':switchPage('cannon');break;case'legacy-learn':switchPage('learn');break;case'legacy-weakness':switchPage('weakness');break;
   case'topic':switchPage('cannon');startCannonGame(d.topic);break;
   case'theory':{switchPage('learn');const mi=KNOWLEDGE_TREE.findIndex(m=>m.topics.some(t=>t.id===d.topic));if(mi>=0){const ti=KNOWLEDGE_TREE[mi].topics.findIndex(t=>t.id===d.topic);const container=document.getElementById('module-topics-'+mi);if(container.dataset.open!=='true')toggleModule(mi);document.getElementById(`topic-body-${mi}-${ti}`).classList.add('open');container.scrollIntoView();}break;}
   case'lesson-quiz':startQuiz('lesson',Number(d.id));break;case'retry':startQuiz('retry');break;case'diagnostic':startQuiz('diagnostic');break;case'quiz':startQuiz(d.mode);break;case'answer':answer(Number(d.choice));break;case'next-question':if(quiz?.answered){quiz.i++;renderQuiz();}break;
   case'dataset':dataset(d.id);break;case'audit':audit();break;case'summary':audit(true);break;
   case'save-note':progress.notes[d.id]=document.getElementById('lesson-note').value;save();showToast('学习记录已保存');break;
   case'complete-lesson':{const note=document.getElementById('lesson-note').value;if(!note.trim()){showToast('请先记录本学时的答案与反思。');break;}progress.notes[d.id]=note;if(!progress.completed.includes(Number(d.id)))progress.completed.push(Number(d.id));save();show('course');break;}
   case'save-paper':progress.paperNotes[d.id]=document.getElementById('paper-'+d.id).value;save();showToast('论文拆解已保存');break;
   case'save-boss':case'submit-boss':{['analysisPlan','methods','results','limitations','aiAudit'].forEach(k=>progress.boss[k]=document.getElementById('boss-'+k).value);save();if(d.action==='submit-boss'){if(Object.values(progress.boss).filter(v=>typeof v==='string'&&v.trim()).length<5){showToast('请完成五部分内容后提交。');break;}download('StatCannon-FinalBoss.json',{format:'statcannon-final-boss',submittedAt:new Date().toISOString(),submission:progress.boss,rubric,grading:'待教师评阅'});}else showToast('Final Boss草稿已保存');break;}
   case'errors':errors();break;case'export':download('StatCannon-learning-'+progress.learnerId+'-'+new Date().toISOString().slice(0,10)+'.json',{format:'statcannon-academy',exportedAt:new Date().toISOString(),progress:{...progress,teacherReports:[]}});break;
   case'import':importFiles(false);break;case'teacher-import':importFiles(true);break;case'teach':lesson(Number(document.getElementById('teacher-lesson').value));break;
   case'timer':{clearInterval(timer);const mins=Number(document.getElementById('timer-minutes').value);if(!Number.isFinite(mins)||mins<1||mins>120){showToast('请输入1–120分钟');break;}const end=Date.now()+mins*60000;const tick=()=>{const left=Math.max(0,Math.ceil((end-Date.now())/1000)),el=document.getElementById('timer-output');if(!el){clearInterval(timer);return;}el.textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;if(left===0){clearInterval(timer);showToast('本环节时间到');}};tick();timer=setInterval(tick,1000);break;}
   case'stop-timer':clearInterval(timer);document.getElementById('timer-output').textContent='已停止';break;
 }});
 document.addEventListener('input',e=>{if(e.target.id==='lesson-note'){progress.notes[progress.lesson]=e.target.value;save();}else if(e.target.id.startsWith('paper-v3-paper-')){progress.paperNotes[e.target.id.slice(6)]=e.target.value;save();}else if(e.target.id.startsWith('boss-')){progress.boss[e.target.id.slice(5)]=e.target.value;save();}});
 window.addEventListener('popstate',routeFromLocation);routeFromLocation();
})();
