/* Learning loop: scores, completed study sessions, targeted revision and honest reminders. */
(() => {
 const key='statcannon-learning-loop-v1';
 let data={visits:{},pending:[],auto:false};
 try {data={...data,...JSON.parse(localStorage.getItem(key)||'{}')}} catch {}
 const persist=()=>{try{localStorage.setItem(key,JSON.stringify(data))}catch{showToast('学习记录无法保存，请检查浏览器存储空间')}};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const topics=()=>KNOWLEDGE_TREE.flatMap(m=>m.topics.map(t=>({m,t,score:getTopicMastery(t.id)})));
 const grade=s=>s===null?{label:'未测试',color:'#64748b',width:0}:s<60?{label:'薄弱点',color:'#b91c1c',width:100-s}:s<85?{label:'待巩固',color:'#a16207',width:100-s}:{label:'已掌握',color:'#15803d',width:100-s};
 window.STATCANNON_GRADE=grade;
 function jump(id){closeQuestion();switchPage('learn');initLearn();const mi=KNOWLEDGE_TREE.findIndex(m=>m.topics.some(t=>t.id===id));if(mi<0)return;const ti=KNOWLEDGE_TREE[mi].topics.findIndex(t=>t.id===id);const el=document.getElementById('module-topics-'+mi);el.style.display='block';el.dataset.open='true';const body=document.getElementById(`topic-body-${mi}-${ti}`);body.classList.add('open');body.scrollIntoView({block:'center'});}
 function rows(items,select=false){return items.map(({m,t,score})=>{const g=grade(score);return `<article class="ll-row">${select?`<input type="checkbox" class="ll-pick" value="${t.id}" aria-label="选择${esc(t.name)}">`:''}<div class="ll-main"><strong>${esc(t.name)}</strong><p>${esc(m.name)}</p><div class="ll-track" aria-label="待补强程度"><div style="width:${g.width}%;background:${g.color}"></div></div></div><div class="ll-status"><strong style="color:${g.color}">${g.label}${score===null?'':' · '+score+'分'}</strong><p>已完成学习 ${Number(data.visits[t.id])||0} 次</p></div><button class="btn btn-dim" data-ll-topic="${t.id}" aria-label="返回${esc(t.name)}知识树">📖 补学</button></article>`}).join('')}
 const legend='<p>掌握程度：绿色 ≥85分 · 黄色 60–84分 · 红色 &lt;60分 · 灰色未测试。条长＝100－测试分数，越长越需补强；分数按累计作答正确率计算，答题速度不影响分层。</p>';
 renderWeakness=()=>{document.getElementById('weakness-chart').innerHTML=legend+rows(topics().sort((a,b)=>(a.score??101)-(b.score??101)))};
 generateWeaknessPlan=()=>{const el=document.getElementById('plan-output');el.style.display='block';const weak=topics().filter(x=>x.score!==null&&x.score<60);el.innerHTML='<h4>优先补学</h4>'+ (weak.length?rows(weak):'<p>暂无低于60分的知识点，未测试的知识点请先完成测试。</p>')};
 generateFullPlan=()=>{document.getElementById('plan-output-full').innerHTML=`<h3>个性化学习大纲</h3>${legend}<p>次数只统计完整完成五步学习，不统计展开卡片或刷新页面。本机保存。</p>${rows(topics().sort((a,b)=>(a.score??101)-(b.score??101)),true)}<div class="ll-actions"><button class="btn btn-primary" data-ll-send>发送选中知识点到手机</button><button class="btn btn-dim" data-ll-share>分享选中学习内容</button><label><input type="checkbox" id="ll-auto" ${data.auto?'checked':''}> 测试结束后自动提醒薄弱点</label></div><p id="ll-delivery" role="status">${data.pending.length?'有 '+data.pending.length+' 个知识点待发送。':''}手机自动推送尚未接通；开启后会在本机生成待发送学习提醒。可通过系统分享选择微信等应用发送。</p><div id="ll-preview"></div>`};
 const complete=completeLearning;
 completeLearning=function(){const id=state.learning?.topicId;if(id){data.visits[id]=(Number(data.visits[id])||0)+1;persist()}return complete.apply(this,arguments)};
 function collect(){if(!data.auto)return;data.pending=topics().filter(x=>x.score!==null&&x.score<60).map(x=>x.t.id);persist();if(data.pending.length)showToast('发现 '+data.pending.length+' 个薄弱点，学习方案中已生成待发送提醒（尚未发送到手机）')}
 const close=closeQuestion;closeQuestion=function(){const active=!!qSequenceState;const result=close.apply(this,arguments);if(active)collect();return result};
 const end=endCannonGame;endCannonGame=function(){const active=state.gameActive;const result=end.apply(this,arguments);if(active)collect();return result};
 function selected(){return [...document.querySelectorAll('.ll-pick:checked')].map(x=>x.value)}
 function message(ids){return topics().filter(x=>ids.includes(x.t.id)).map(({m,t,score})=>`${t.name}（${score===null?'未测试':score+'分'}）\n学习内容：${t.summary}\n教学大纲：${t.points.join('；')}\n所属模块：${m.name}\n补学链接：${new URL('#learn-topic='+t.id,document.baseURI).href}`).join('\n\n')}
 function prepare(ids){if(!ids.length){showToast('请先选择知识点');return null}const text=message(ids);const el=document.getElementById('ll-preview');if(el){el.innerHTML='<h4>待发送内容</h4><pre></pre>';el.querySelector('pre').textContent=text}return text}
 sendSMSReminder=function(){const ids=selected();const targets=ids.length?ids:topics().filter(x=>x.score!==null&&x.score<60).map(x=>x.t.id);if(!prepare(targets))return;data.pending=targets;persist();showToast('提醒内容已生成，尚未发送：需要接通手机消息服务。可点击“分享选中学习内容”。')};
 document.addEventListener('click',async e=>{const jumpButton=e.target.closest('[data-ll-topic]');if(jumpButton){e.stopPropagation();jump(jumpButton.dataset.llTopic)}if(e.target.closest('[data-ll-send]'))sendSMSReminder();if(e.target.closest('[data-ll-share]')){const ids=selected();const text=prepare(ids.length?ids:data.pending);if(!text)return;try{if(navigator.share){await navigator.share({title:'统计大炮个性化学习方案',text});showToast('已交给系统分享，请在所选应用中确认发送')}else{await navigator.clipboard.writeText(text);showToast('内容已复制，请粘贴到微信等应用发送')}}catch(err){showToast(err.name==='AbortError'?'已取消分享':'无法分享，请手动复制下方学习内容')}}});
 document.addEventListener('change',e=>{if(e.target.id==='ll-auto'){data.auto=e.target.checked;persist()}});
 const css=document.createElement('style');css.textContent='.ll-row{display:flex;align-items:center;gap:14px;padding:18px 0;border-bottom:1px solid #cbd5e1;flex-wrap:wrap}.ll-main{flex:1;min-width:180px}.ll-row p{font-size:14px;margin:5px 0}.ll-track{height:10px;background:#e2e8f0;border-radius:8px;overflow:hidden}.ll-track>div{height:100%}.ll-status{min-width:150px}.ll-actions{display:flex;gap:12px;flex-wrap:wrap;margin:22px 0}.ll-pick{width:20px;height:20px}#ll-preview pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}.ll-chapters details{margin:12px 0;padding:12px;border:1px solid #cbd5e1;border-radius:8px}.ll-chapters summary{cursor:pointer;font-weight:600}.ll-chapters li{margin:8px 0}@media(max-width:600px){.ll-status{min-width:100px}.ll-row{gap:10px}.ll-main{min-width:160px}}';document.head.appendChild(css);
 const resources=renderResources;
 renderResources=async function(){resources();const container=document.getElementById('resources-container');const section=document.createElement('section');section.className='card ll-chapters';section.innerHTML='<h2>方积乾《卫生统计学》主要章节</h2><p>依据您提供的教材文档整理。细分目录收在 Other 中；知识树学习卡与教材章节分别标识。</p><div>正在读取教材目录…</div>';container.prepend(section);try{const res=await fetch(new URL('academy/textbook-chapters.json',document.baseURI));if(!res.ok)throw Error();const chapters=await res.json();section.lastElementChild.innerHTML=chapters.map(c=>`<details><summary>${esc(c.title)}</summary><details><summary>Other · 细分内容（${c.sections.length}项）</summary><ul>${c.sections.map(x=>'<li>'+esc(x)+'</li>').join('')}</ul></details><p>在知识树中补学相关内容：</p>${topics().filter(x=>c.title.toLowerCase().includes(x.t.name.toLowerCase())||x.t.name.toLowerCase().includes(c.title.replace(/基础|分析|与相关/g,'').toLowerCase())).map(x=>`<button class="btn btn-dim" data-ll-topic="${x.t.id}">📖 ${esc(x.t.name)}</button>`).join('')||'<button class="btn btn-dim" onclick="switchPage(\'learn\')">📖 浏览知识树</button>'}</details>`).join('')}catch{section.lastElementChild.textContent='教材目录暂时无法加载，请稍后重试。'}};
 const hash=()=>{const m=location.hash.match(/^#learn-topic=(t\d+)$/);if(m)jump(m[1])};window.addEventListener('hashchange',hash);hash();
 if(document.getElementById('page-weakness').classList.contains('active'))renderWeakness();
 if(document.getElementById('page-plan').classList.contains('active'))generateFullPlan();
})();
