(function(){
 'use strict';
 const base=new URL('.',document.baseURI),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const starter=[['统计推断','P值大于0.05能说明两组相同吗？'],['研究设计','配对t检验与独立样本t检验有什么区别？'],['统计描述','标准差和标准误有什么区别？'],['生存分析','Cox回归有什么前提条件？']];
 let service=null,servicePending=null;
 async function checkService(){if(service)return service;if(!servicePending)servicePending=fetch(new URL('api/textbook/status',base),{signal:AbortSignal.timeout(3000)}).then(r=>r.ok?r.json():null).then(data=>service=data?.modelReady?data:{modelReady:false}).catch(()=>service={modelReady:false});return servicePending;}
 let engine=null,pending=null,chapterId='',history=[],context=null,busy=false,controller=null;
 async function load(){if(engine)return engine;if(!pending)pending=fetch(new URL('academy/textbook/corpus.json',base)).then(r=>{if(!r.ok)throw Error('教材读取失败');return r.json();}).then(data=>engine=StatTextbook.create(data)).catch(e=>{pending=null;throw e;});return pending;}
 function shell(){return `<div class="tb-shell"><header class="tb-header"><div><h1>教材答疑</h1><p>《卫生统计学》 · 方积乾主编 · 结合教材理解统计问题</p></div><span class="tb-bookmark">有据可查</span></header><div class="tb-layout"><aside class="tb-library"><h2>你的教材</h2><p>从概念到方法，再回到研究问题。</p><label for="tb-chapter">提问范围</label><select id="tb-chapter" disabled><option value="">全部章节</option></select><details><summary>浏览20章目录</summary><ul class="tb-chapter-list" id="tb-chapter-list"></ul></details><p class="tb-note">正文20章可检索。引用定位到上传Markdown的原始行号。超长统计用表与随书光盘内容不用于自动答疑。</p><p class="tb-note">文件前言对应第7版；OCR公式与表格请核对原版。模型未连接时使用教材检索；连接后显示实际本地模型名称。</p><a href="${new URL('course/',base)}" data-route="course">返回16学时课程 →</a></aside><section class="tb-workspace" aria-label="教材问答"><div class="tb-toolbar"><span id="tb-status" class="tb-status" role="status">正在载入教材…</span><button type="button" class="tb-button" id="tb-reset">新问题</button></div><div class="tb-conversation" id="tb-conversation" role="log" aria-label="问答记录" aria-live="polite" aria-relevant="additions"></div><form class="tb-composer" id="tb-form"><label for="tb-question">你想了解什么？</label><div class="tb-input-row"><textarea id="tb-question" rows="2" maxlength="800" placeholder="例如：同一批患者治疗前后血压比较，应该用什么检验？" aria-describedby="tb-hint" required></textarea><button class="tb-send" id="tb-submit" type="submit">提问 ↑</button></div><p class="tb-hint" id="tb-hint"><span>Enter提问 · Shift+Enter换行 · 可继续追问</span><span id="tb-count">0/800</span></p></form></section></div></div>`;}
 function welcome(){return `<div class="tb-welcome"><h2>把问题带回教材，找到理解的依据。</h2><p>输入概念或研究场景。你可以接着问适用条件、查看教材例题，也可以展开引用原文核对。</p><div class="tb-prompts">${starter.map(([label,q])=>`<button type="button" data-tb-ask="${esc(q)}"><span>${label}</span>${esc(q)}</button>`).join('')}</div><p class="tb-empty-scope">问答只在本次页面会话中保留；刷新后清空。</p></div>`;}
 // All OCR and user content is text-escaped. No remote images, raw HTML or scripts.
 function passage(text){return esc(text).replace(/\$\$([\s\S]*?)\$\$|\$([^$]+)\$/g,(_,block,inline)=>`<span class="tb-formula">${block||inline}</span>`);}
 function reply(turn,i){const a=turn.answer;
  if(a.status!=='ok')return `<article class="tb-reply"><div class="tb-reply-label">教材答疑</div><p class="tb-error">${esc(a.message)}</p>${a.status==='error'?'<button type="button" class="tb-button" data-tb-retry="'+i+'">重新载入并提问</button>':''}${chapterId?'<button type="button" class="tb-button" data-tb-all="'+i+'">在全部章节中重试</button>':''}</article>`;
  return `<article class="tb-reply"><div class="tb-reply-label">${a.mode==='textbook-local-model'?'本地模型 · '+esc(a.model):a.mode==='textbook-guided'?'教材要点解读':'教材相关段落'}</div>${a.modelNotice?`<p class="tb-context">${esc(a.modelNotice)}</p>`:''}${a.followup?`<p class="tb-context">继续讨论：${esc(a.resolvedQuestion)}</p>`:''}${a.explanation?.length?`<ul>${a.explanation.map(x=>`<li>${esc(x.text)}${(x.sourceNumbers||[x.sourceNumber]).map(n=>`<button type="button" class="tb-cite" data-tb-cite="tb-source-${i}-${n}" aria-label="查看依据${n}">[${n}]</button>`).join('')}</li>`).join('')}</ul>`:`<p>${esc(a.message)}</p>`}${a.prompt?`<p class="tb-context">${esc(a.prompt)}</p>`:''}<h3>教材依据 · 点击展开原文</h3>${a.sources.map(s=>`<div class="tb-evidence"><div class="tb-ref-title">[${s.number}] ${esc(s.chapter)} · ${esc(s.heading)}</div><blockquote>${passage(s.excerpt)}</blockquote><details id="tb-source-${i}-${s.number}"><summary>查看引用原文与位置</summary><span class="tb-line">${esc(s.section)} · Markdown第${s.startLine}–${s.endLine}行（非书本页码）</span><div class="tb-source">${passage(s.text)}</div></details></div>`).join('')}<div class="tb-followups">${a.suggestions.map(q=>`<button class="tb-button" type="button" data-tb-follow="${i}" data-tb-question="${esc(q)}">${esc(q)}</button>`).join('')}</div></article>`;
 }
 function draw(){const box=document.getElementById('tb-conversation');if(!box)return;box.innerHTML=history.length?history.map((t,i)=>`<div class="tb-question">${esc(t.question)}</div>${t.answer?reply(t,i):'<div class="tb-reply" role="status">正在检索教材依据…</div>'}`).join(''):welcome();box.scrollTop=box.scrollHeight;const send=document.getElementById('tb-submit');send.disabled=busy;send.textContent=busy?'查找中…':'提问 ↑';document.getElementById('tb-reset').disabled=busy;}
 function options(){if(!engine)return;const select=document.getElementById('tb-chapter');if(!select)return;select.innerHTML='<option value="">全部章节</option>'+engine.meta.chapters.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('');select.value=chapterId;select.disabled=busy;document.getElementById('tb-chapter-list').innerHTML=engine.meta.chapters.map(c=>`<li><button type="button" data-tb-chapter="${c.id}" aria-current="${c.id===chapterId}">${esc(c.title)}</button></li>`).join('');document.getElementById('tb-status').textContent=service?.modelReady?`本地模型 · ${service.model}`:`教材检索 · ${engine.meta.chapterCount}章 · 未启用大模型`;}
 async function ask(q,followContext=null){q=q.trim();if(!q||busy)return;if(q.length>800)return;busy=true;const turn={question:q,answer:null};history.push(turn);if(history.length>16)history.shift();const field=document.getElementById('tb-question');if(field){field.value='';document.getElementById('tb-count').textContent='0/800';}draw();options();
  try{const e=await load(),backend=await checkService(),payload={question:q,chapterId,context:followContext||context};if(backend.modelReady){try{const r=await fetch(new URL('api/textbook/ask',base),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(50000)});if(!r.ok)throw Error();turn.answer=await r.json();if(!turn.answer.status||!Array.isArray(turn.answer.sources))throw Error();}catch{turn.answer={...e.answer(q,payload),modelNotice:'模型服务暂不可用，先显示教材检索答复。'};}}else{turn.answer=e.answer(q,payload);}context=turn.answer.context||null;}
  catch{turn.answer={status:'error',message:'教材暂时未能载入。请检查网络后点击重试；已经载入的教材可在本次会话继续使用。',sources:[]};}
  finally{busy=false;options();draw();}
 }
 async function mount(root){controller?.abort();controller=new AbortController();const signal=controller.signal;
  const form=root.querySelector('#tb-form');if(!form)return;
  form.addEventListener('submit',e=>{e.preventDefault();ask(root.querySelector('#tb-question').value);},{signal});
  root.querySelector('#tb-question').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&e.keyCode!==229){e.preventDefault();form.requestSubmit();}},{signal});
  root.querySelector('#tb-question').addEventListener('input',e=>{root.querySelector('#tb-count').textContent=e.target.value.length+'/800';},{signal});
  root.querySelector('#tb-chapter').addEventListener('change',e=>{chapterId=e.target.value;context=null;options();},{signal});
  root.addEventListener('click',e=>{
    const b=e.target.closest('button');if(!b)return;
    if(b.id==='tb-reset'&&!busy){history=[];context=null;draw();root.querySelector('#tb-question').focus();}
    if(b.dataset.tbAsk)ask(b.dataset.tbAsk);
    if(b.dataset.tbFollow!==undefined){const turn=history[Number(b.dataset.tbFollow)];if(turn?.answer?.context)ask(b.dataset.tbQuestion,turn.answer.context);}
    if(b.dataset.tbRetry!==undefined){const turn=history[Number(b.dataset.tbRetry)];if(turn)ask(turn.question);}
    if(b.dataset.tbAll!==undefined&&!busy){const turn=history[Number(b.dataset.tbAll)];chapterId='';context=null;options();if(turn)ask(turn.question);}
    if(b.dataset.tbChapter&&!busy){chapterId=b.dataset.tbChapter;context=null;options();}
    if(b.dataset.tbCite){const detail=document.getElementById(b.dataset.tbCite);if(detail){detail.open=true;detail.scrollIntoView({block:'nearest',behavior:'smooth'});}}
  },{signal});
  draw();service=null;servicePending=null;try{await Promise.all([load(),checkService()]);if(signal.aborted||!document.getElementById('tb-chapter'))return;options();
   const q=new URL(location.href).searchParams.get('q');if(q&&!history.length){const input=root.querySelector('#tb-question');input.value=q.slice(0,800);root.querySelector('#tb-count').textContent=input.value.length+'/800';}
  }catch{const status=document.getElementById('tb-status');if(status)status.textContent='教材加载失败，可点击提问重试';}
 }
 window.TextbookQA={shell,mount};
})();
