/* Independent, transparent planning approximations. Not the proprietary PASS engine. */
(function(root){'use strict';
const version='1.0.0';
function fail(s){throw new Error(s);}
function phi(x){const z=Math.abs(x),t=1/(1+.2316419*z),d=.3989422804014327*Math.exp(-z*z/2),p=1-d*t*(.319381530+t*(-.356563782+t*(1.781477937+t*(-1.821255978+t*1.330274429))));return x<0?1-p:p;}
function quantile(p){if(!(p>0&&p<1))fail('概率必须在0与1之间。');let l=-10,h=10;for(let i=0;i<90;i++){const m=(l+h)/2;if(phi(m)<p)l=m;else h=m;}return(l+h)/2;}
function logGamma(z){const p=[676.5203681218851,-1259.1392167224028,771.32342877765313,-176.61502916214059,12.507343278686905,-.13857109526572012,9.9843695780195716e-6,1.5056327351493116e-7];if(z<.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-logGamma(1-z);z--;let x=.99999999999980993;for(let i=0;i<p.length;i++)x+=p[i]/(z+i+1);const t=z+7.5;return .9189385332046727+(z+.5)*Math.log(t)-t+Math.log(x);}
function gammaP(a,x){if(x<=0)return 0;const f=Math.exp(-x+a*Math.log(x)-logGamma(a));if(x<a+1){let sum=1/a,term=sum;for(let i=1;i<10000;i++){term*=x/(a+i);sum+=term;if(Math.abs(term)<Math.abs(sum)*1e-14)break;}return Math.min(1,sum*f);}let b=x+1-a,c=1e300,d=1/b,h=d;for(let i=1;i<10000;i++){const an=-i*(i-a);b+=2;d=an*d+b;if(Math.abs(d)<1e-300)d=1e-300;c=b+an/c;if(Math.abs(c)<1e-300)c=1e-300;d=1/d;const delta=d*c;h*=delta;if(Math.abs(delta-1)<1e-14)break;}return Math.max(0,Math.min(1,1-f*h));}
function chiCDF(x,df){return gammaP(df/2,x/2);}
function chiQuantile(p,df){let l=0,h=100;while(chiCDF(h,df)<p)h*=2;for(let i=0;i<80;i++){const m=(l+h)/2;if(chiCDF(m,df)<p)l=m;else h=m;}return(l+h)/2;}
function ncChiCDF(x,df,lambda){if(lambda<1e-12)return chiCDF(x,df);if(lambda>10000)return 0;const mu=lambda/2,k=Math.floor(mu),w=Math.exp(-mu+k*Math.log(mu)-logGamma(k+1));let sum=w*chiCDF(x,df+2*k),mass=w,ww=w;for(let j=k-1;j>=0;j--){ww*=((j+1)/mu);sum+=ww*chiCDF(x,df+2*j);mass+=ww;}ww=w;for(let j=k+1;j<k+10000;j++){ww*=mu/j;sum+=ww*chiCDF(x,df+2*j);mass+=ww;if(ww<1e-15&&j>mu+10)break;}return Math.max(0,Math.min(1,sum/mass));}
const dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0);
const transpose=a=>a[0].map((_,i)=>a.map(r=>r[i]));
const matmul=(a,b)=>{const bt=transpose(b);return a.map(r=>bt.map(c=>dot(r,c)));};
function inverse(a){const n=a.length,m=a.map((r,i)=>[...r,...Array.from({length:n},(_,j)=>+(i===j))]);for(let i=0;i<n;i++){let k=i;for(let j=i+1;j<n;j++)if(Math.abs(m[j][i])>Math.abs(m[k][i]))k=j;if(Math.abs(m[k][i])<1e-12)fail('协方差矩阵不可逆。');[m[i],m[k]]=[m[k],m[i]];const p=m[i][i];m[i]=m[i].map(v=>v/p);for(let j=0;j<n;j++)if(j!==i){const f=m[j][i];m[j]=m[j].map((v,c)=>v-f*m[i][c]);}}return m.map(r=>r.slice(n));}
function positiveDefinite(a){const n=a.length,L=Array.from({length:n},()=>Array(n).fill(0));for(let i=0;i<n;i++)for(let j=0;j<=i;j++){let v=a[i][j];for(let k=0;k<j;k++)v-=L[i][k]*L[j][k];if(i===j){if(v<=1e-10)fail('协方差矩阵必须正定。');L[i][j]=Math.sqrt(v);}else L[i][j]=v/L[j][j];}}
function covariance(sd,rho,structure){if(!['CS','AR1'].includes(structure))fail('请选择CS或AR(1)。');const n=sd.length;if(n<2||n>8||sd.some(x=>!Number.isFinite(x)||x<=0))fail('重复测量需要2–8次测量，每次SD须为正数。');if(!(Math.abs(rho)<1)||(structure==='CS'&&rho<=-1/(n-1)))fail('相关系数超出正定协方差允许范围。');const a=sd.map((s,i)=>sd.map((t,j)=>s*t*(i===j?1:structure==='CS'?rho:Math.pow(rho,Math.abs(i-j)))));positiveDefinite(a);return a;}
function validate(p){for(const key of ['alpha','power','ratio','dropout'])if(!Number.isFinite(p[key]))fail('请完整填写数值参数。');if(!(p.alpha>0&&p.alpha<.5))fail('α应在0和0.5之间。');if(!(p.power>.5&&p.power<1))fail('Power应在0.5和1之间。');if(!(p.ratio>=.1&&p.ratio<=10))fail('本教学引擎分配比范围为0.1–10。');if(!(p.dropout>=0&&p.dropout<.8))fail('失访率须在0至0.8之间（不含0.8）。');if(!['mean','binary','cohort','casecontrol','repeated'].includes(p.kind))fail('未支持的计算类型。');if(!['superiority','noninferiority','equivalence'].includes(p.test))fail('请选择检验目标。');}
function setup(p){validate(p);let delta,vT,vC,sigma,contrast,df=1,q=0,eps=null;
 if(p.kind==='repeated'){
  if(!Array.isArray(p.muT)||!Array.isArray(p.muC)||!Array.isArray(p.sd)||p.muT.length!==p.muC.length||p.muT.length!==p.sd.length||p.muT.some(x=>!Number.isFinite(x))||p.muC.some(x=>!Number.isFinite(x)))fail('两组轨迹和SD必须长度一致且为有限数值。');
  if(p.test!=='superiority')fail('本重复测量模块仅实现优效性。');
  const m=p.sd.length;if(p.m!==m||!Array.isArray(p.months)||p.months.length!==m||p.months.some((x,i)=>!Number.isFinite(x)||(i>0&&x<=p.months[i-1])))fail('测量次数、访视月份与轨迹长度须一致，月份须递增。');if(p.cov==='AR1'&&p.months.some((x,i)=>i>1&&Math.abs((x-p.months[i-1])-(p.months[1]-p.months[0]))>1e-8))fail('本版AR(1)要求等间隔访视。');if(p.epsilon!=='na')fail('本Wald规划不使用球形性ε修正。');sigma=covariance(p.sd,p.rho,p.cov);const d=p.muT.map((x,i)=>x-p.muC[i]);
  if(p.objective==='interaction'){contrast=Array.from({length:m-1},(_,i)=>Array.from({length:m},(_,j)=>j===0?-1:j===i+1?1:0));const V=matmul(matmul(contrast,sigma),transpose(contrast)),theta=contrast.map(c=>dot(c,d));q=dot(theta,inverse(V).map(r=>dot(r,theta)));df=m-1;if(q<1e-12)fail('组间差异恒定，时间×组别交互效应为零；不能为非零交互功效求有限样本量。');}
  else{if(!['endpoint','average'].includes(p.objective))fail('请选择主要估计目标。');const c=Array.from({length:m},(_,i)=>p.objective==='average'?1/m:+(i===m-1));contrast=[c];delta=dot(c,d);vT=vC=dot(c,sigma.map(r=>dot(r,c)));}
  const H=Array.from({length:m},(_,i)=>Array.from({length:m},(_,j)=>+(i===j)-1/m)),B=matmul(matmul(H,sigma),H),tr=B.reduce((s,r,i)=>s+r[i],0),tr2=B.reduce((s,r)=>s+dot(r,r),0);eps=tr*tr/((m-1)*tr2);
 }else if(p.kind==='mean'){
  if(!Number.isFinite(p.delta)||!(p.sdT>0&&p.sdC>0)||!Number.isFinite(p.sdT+p.sdC))fail('均值差须为有限数值，两组SD须为正数。');delta=p.delta;vT=p.sdT**2;vC=p.sdC**2;
 }else{let t=p.pT,c=p.pC;if(p.kind==='cohort'){c=p.pC;if(!(p.rr>0&&Number.isFinite(p.rr)))fail('RR须为正数。');t=c*p.rr;}if(p.kind==='casecontrol'){c=p.pC;if(!(p.or>0&&Number.isFinite(p.or)))fail('OR须为正数。');t=p.or*c/(1-c+p.or*c);}if(!(t>0&&t<1&&c>0&&c<1))fail('概率必须严格在0与1之间；请检查RR/OR转换后的概率。');delta=t-c;vT=t*(1-t);vC=c*(1-c);p={...p,pT:t,pC:c};}
 if(p.test==='superiority'&&p.objective!=='interaction'&&Math.abs(delta)<1e-12)fail('预期差异为零，无法计算达到目标功效的有限样本量。');
 if(p.test!=='superiority'){if(!(p.margin>0&&Number.isFinite(p.margin)))fail('界值须为正数。');if(p.kind==='binary'&&p.margin>=1)fail('风险差界值必须小于1。');if(p.test==='noninferiority'){if(!['lower','higher'].includes(p.direction))fail('请说明结局越高还是越低越好。');if((p.direction==='lower'?p.margin-delta:p.margin+delta)<=0)fail('预期差异已落在非劣效边界外，无法达到所需功效。');}else if(Math.abs(delta)>=p.margin)fail('预期差异必须严格位于等效区间内。');}
 const z=quantile(1-p.alpha/(p.test==='superiority'?2:1)),critical=p.objective==='interaction'?chiQuantile(1-p.alpha,df):null;
 function powerAt(nT,nC){const factor=1/nT+1/nC;if(p.objective==='interaction')return 1-ncChiCDF(critical,df,q/factor);const se=Math.sqrt(vT/nT+vC/nC);if(p.test==='noninferiority')return phi((p.direction==='lower'?p.margin-delta:p.margin+delta)/se-z);if(p.test==='equivalence')return Math.max(0,phi((p.margin-delta)/se-z)-phi((-p.margin-delta)/se+z));let se0=se;if(['binary','cohort','casecontrol'].includes(p.kind)){const pooled=(p.pT*nT+p.pC*nC)/(nT+nC);se0=Math.sqrt(pooled*(1-pooled)*factor);}return phi((-z*se0-delta)/se)+1-phi((z*se0-delta)/se);}
 return{p,delta,vT,vC,sigma,contrast,df,q,eps,powerAt};
}
function solve(p){const s=setup({...p});let lo=1,hi=2;const pw=n=>s.powerAt(n,Math.ceil(n*p.ratio));while(pw(hi)<p.power&&hi<1000000)hi=Math.min(1000000,hi*2);if(pw(hi)<p.power)fail('所需样本量超过本教学引擎上限。');while(hi-lo>1){const mid=Math.floor((hi+lo)/2);if(pw(mid)>=p.power)hi=mid;else lo=mid;}const nT=hi,nC=Math.ceil(hi*p.ratio),recruitT=Math.ceil(nT/(1-p.dropout)),recruitC=Math.ceil(nC/(1-p.dropout));return{...s,powerAt:undefined,version,nT,nC,total:nT+nC,recruitT,recruitC,recruitTotal:recruitT+recruitC,achieved:s.powerAt(nT,nC),previousPower:nT>2?s.powerAt(nT-1,Math.ceil((nT-1)*p.ratio)):null};}
const api={version,phi,quantile,chiCDF,chiQuantile,ncChiCDF,covariance,setup,solve};root.PassMath=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
