/* Integrate original sample-size lessons with the existing classroom and mastery system. */
(()=>{'use strict';const L=window.PassLearning,A=window.ACADEMY;
const references=[['DELTA²：目标差异与样本量报告','https://www.bmj.com/content/363/bmj.k3750'],['FDA：多终点与联合成功规则','https://www.fda.gov/regulatory-information/search-fda-guidance-documents/multiple-endpoints-clinical-trials'],['PASS：随访平均差异与协方差','https://www.ncss.com/wp-content/themes/ncss/pdf/Procedures/PASS/Tests_for_Two_Means_in_a_Repeated_Measures_Design.pdf']];
for(const t of L.topics)for(const q of t.questions){window.STATCANNON_OPTION_NOTES[q.id]={q:q.q,choices:Object.fromEntries(q.options.map((o,i)=>[o,q.optionReasons[i]]))};}
const review=L.topics.map(t=>{const orig=t.questions[t.id==='t52'?1:t.id==='t48'?1:0];return {...orig,id:'pass-review-'+t.id,q:'模拟审稿情境：'+orig.q,mode:'reviewer',sampleSize:true,skill:5,topic:t.id};});
for(const q of review){A.questions.push(q);window.STATCANNON_OPTION_NOTES[q.id]={q:q.q,choices:Object.fromEntries(q.options.map((o,i)=>[o,q.optionReasons[i]]))};}
const papers=[
{id:'v3-paper-pass-oviva',title:'OVIVA：非劣效界值与方案变更',journal:'真实研究 · NEJM, 2019',doi:'10.1056/NEJMoa1710926',url:'https://www.nejm.org/doi/full/10.1056/NEJMoa1710926',design:'骨关节感染治疗的非劣效RCT',focus:'先验事件率、绝对风险差界值、变更透明度',tasks:['找到Statistical Analysis中的原始样本量假设：预期事件率、初始界值、单双侧α、功效及失访；区分原计划与最后采用的界值。','核对界值从5个百分点变为7.5个百分点的论证、时点和批准程序；不要将“发生变更”本身等同于不规范。','若迁移为另一人群，哪些事件率、界值与临床依据需要重新论证？写出一条含证据位置的审稿意见。'],answer:'原文报告了初始5%事件率、5个百分点界值、单侧α=0.05、90%功效、10%失访，并说明界值调整至7.5个百分点及批准。教学重点是区分原始假设、变更与实施；本平台模拟参数不是原论文样本量的复现。'},
{id:'v3-paper-pass-eolia',title:'EOLIA：提前停止后如何解读精度',journal:'真实研究 · NEJM, 2018',doi:'10.1056/NEJMoa1800385',url:'https://www.nejm.org/doi/full/10.1056/NEJMoa1800385',design:'重症ARDS的ECMO随机试验',focus:'计划样本量、中期监测、实际入组与不确定性',tasks:['阅读原文及方案，分别提取最大计划样本量、停止规则、实际入组人数和主要结局的效应区间；不要用实际N冒充原计划。','判断停止原因及规则是否预先规定；区分“试验未证明优效”与“证明两组相同”。','若审稿人要求用观察效应重新计算功效来证明无效，你会如何回应？'],answer:'原文报告249名参与者，并说明按方案在达到最大计算样本量的75%后停止。提前停止的依据、结局区间和交叉治疗等影响需一起评估；不显著本身不证明无效。这里没有把另设教学缺陷归于原论文。'},
{id:'v3-paper-pass-delta',title:'DELTA²：目标差异不能只由招募上限决定',journal:'方法学指南 · BMJ, 2018',doi:'10.1136/bmj.k3750',url:'https://www.bmj.com/content/363/bmj.k3750',design:'目标差异选择与样本量报告指南，不是RCT结果论文',focus:'临床重要性、现实预期、参数证据与敏感性',tasks:['找到关于选择和说明目标差异的建议；分别解释“值得检出的差异”和“预期真实差异”。','选取自己领域的先验文献，核对人群、结局、时间窗、SD/事件率；列出至少一个不确定参数。','用自主计算入口对可信效应范围做敏感性分析，解释最终采用哪一组假设，而非只报告最小N。'],answer:'目标差异是规划中的关键判断，应有可说明的依据。指南用于审查选择和报告过程，不为所有研究提供一个统一效应值。预实验、文献或Meta分析的估计仍需评估适用性与不确定性。'},
{id:'v3-paper-pass-rm',title:'模拟方案剖析：6个月差异，还是1、3、6个月都有效？',journal:'原创模拟案例 · 非真实论文',doi:'',url:'https://www.fda.gov/regulatory-information/search-fda-guidance-documents/multiple-endpoints-clinical-trials',sourceLabel:'核对方法依据：FDA多终点指南',design:'连续结局重复测量RCT的模拟方案',focus:'主要时点、逐时点检验、平均与交互的混淆',tasks:['模拟方案称主要结局为6个月组间差，却以三时点平均差计算N。指出估计目标不一致及修正方案。','如果三个时点分别进行确证性判断，应预设怎样的多重性策略？若要求三次均成功，联合功效与各时点功效有何不同？','若访视为1、3、6个月，检查等间隔AR(1)假设是否可直接使用；说明需要补充的相关及分析信息。'],answer:'原设定的末次目标不能被平均差或交互目标替代。多重性策略取决于声明规则；全成功的交并规则不需机械分摊α，但须按联合功效规划。1、3、6个月不等间隔，当前自主计算的等间隔AR(1)限制不能忽略。此为独立模拟情境，不是FDA文件中的试验。'},
{id:'v3-paper-pass-source',title:'模拟论文审阅：SE冒充SD与“软件算得200例”',journal:'原创模拟案例 · 非真实论文',doi:'',url:'https://www.bmj.com/content/363/bmj.k3750',sourceLabel:'核对方法依据：DELTA²',design:'两组连续结局RCT的模拟稿件',focus:'输入来源、失访膨胀、可复现方法段落',tasks:['模拟稿件从文献表中的SE取值作为SD，按10%失访将N乘1.1。分别解释方向和后果。','要求作者补充参数来源、结局时点、单双侧、Power、分配比、计算方法及正确的失访调整。','若实际只运行本站近似引擎，如何修改“采用PASS软件计算”的表述？写一段可执行major comment。'],answer:'SE与SD不同；误用较小SE通常使N偏小。失访应使用ceil(n/(1−r))。审稿应要求匹配主要分析、核查输入来源、重新计算并更新报告；不能伪称用了未实际运行的软件。模拟错误不属于引用指南作者。'}
];A.papers.push(...papers);L.papers=papers;L.review=review;
L.panel=function(){return `<section class="ac-card"><h2>样本量理论 · 原创补充章</h2><p>9个知识点、36道练习、9个模拟审稿问题。这里是独立编写的教学补充，不是方积乾教材原文或原书引文。</p><div class="ac-row"><button class="ac-btn primary" data-action="quiz" data-mode="sample-theory">样本量专项诊断（每知识点1题）</button><button class="ac-btn" data-action="quiz" data-mode="sample-review">样本量审稿专项</button><button class="ac-btn" data-action="legacy-weakness">查看薄弱点与补学</button><a class="ac-btn" data-route="pass" href="pass/">回到计算与自主研究</a></div>${L.topics.map(t=>{const score=typeof getTopicMastery==='function'?getTopicMastery(t.id):null;return `<article class="ac-card"><h3>${t.name}</h3><p>${t.summary}</p><p>掌握情况：${score===null?'未测试':score+'% · '+(score<60?'优先补学':score<85?'待巩固':'已掌握')}</p><details><summary>阅读核心理论与公式</summary><ul>${t.points.map(p=>`<li style="margin:10px 0;line-height:1.8">${p}</li>`).join('')}</ul></details><button class="ac-btn" data-action="theory" data-topic="${t.id}">打开知识卡</button><button class="ac-btn" data-action="topic" data-topic="${t.id}">练习本知识点</button></article>`;}).join('')}<p>答题结果按知识点计入累计正确率；低于60%列为薄弱点，60%–84%待巩固。阅读或计算成功不自动计为掌握。</p>${references.map(([n,u])=>`<p><a href="${u}" target="_blank" rel="noopener">${n}</a></p>`).join('')}</section>`;};
})();
