(function(){'use strict';
const pct=x=>+(x*100).toFixed(4)+'%';
function create(c,r){const p=r.p,refsZh='\n\n参考文献与参数依据（请替换占位内容，不应直接引用本教学案例作为先验证据）：\n[1] [主要结局参数来源：与本研究人群、干预/暴露、结局定义和随访时点高度相关的研究；填写作者、题名、期刊、年份、卷(期)、页码及DOI。若来自预实验，请描述样本量、实施时间、估计值和不确定性；未发表预实验可在正文或附录说明。]\n[2] [若使用自行开展的系统综述/Meta分析：填写检索截止日期、纳入研究及合并方法，并引用综述或附录；明确是合并事件率、均值差、SD还是相对效应，不得直接将RR/OR/HR当事件概率。]\n[3] [方法学依据：填写与实际使用的样本量公式、检验或模拟方法相匹配的文献及软件文档。]\n[4] [失访率依据：相似研究、预实验或本中心历史资料；注明来源及观察窗口。]',refsEn='\n\nReferences and parameter sources (replace all placeholders; the teaching case is not prior empirical evidence):\n[1] [Source of outcome assumptions: study closely matching the target population, intervention/exposure, outcome definition and follow-up; provide authors, title, journal, year, volume(issue), pages and DOI. For a pilot study, report its sample size, dates, estimates and uncertainty; describe unpublished pilot data in the text or an appendix.]\n[2] [If a de novo systematic review/meta-analysis was used: provide the search cutoff, included studies, pooling method and review/appendix citation. Specify whether event rates, mean differences, SDs or relative effects were pooled; do not substitute RR/OR/HR directly for event probabilities.]\n[3] [Methodological reference and software documentation matching the calculation actually performed.]\n[4] [Evidence for attrition: comparable studies, pilot data or local historical records, including the observation window.]';
let zh='',en='';
if(p.kind==='mean') {zh=`预计组T与组C的主要结局均值差（T−C）为${p.delta} [结局单位]，两组标准差分别为${p.sdT}和${p.sdC} [参数来自预实验、相关文献或系统综述/Meta分析，说明估计方法及引用位置：1或2]。`;en=`The anticipated mean difference in the primary outcome (T minus C) was ${p.delta} [outcome units], with standard deviations of ${p.sdT} and ${p.sdC}, respectively [justify using pilot data, relevant studies, or a systematic review/meta-analysis; cite 1 or 2]. `;}
else if(p.kind==='repeated'){const goals={endpoint:['末次访视的组间均值差','the between-group mean difference at the last visit'],average:['纳入访视的等权平均组间差异','the equally weighted average between-group difference across the included visits'],interaction:['组别与时间的交互效应','the group-by-time interaction']};zh=`主要估计目标为${goals[p.objective][0]}。纳入治疗后第${p.months.join('、')}个月的${p.m}次测量，预计组T均值依次为${p.muT.join('、')}，组C为${p.muC.join('、')}，各访视边际标准差为${p.sd.join('、')} [填写结局及单位；均值轨迹与SD的来源和依据：1或2]。假设两组共享${p.cov==='CS'?'复合对称（CS）':'一阶自回归AR(1)'}协方差结构，${p.cov==='CS'?'任意访视间':'相邻等间隔访视间'}相关系数为${p.rho} [相关系数与结构的经验依据；若无可靠数据，应报告敏感性分析]。`;en=`The primary estimand was ${goals[p.objective][1]}. The ${p.m} post-treatment assessments were scheduled at months ${p.months.join(', ')}. Expected means were ${p.muT.join(', ')} in group T and ${p.muC.join(', ')} in group C, with marginal standard deviations of ${p.sd.join(', ')} [specify outcome units and empirical sources for trajectories and SDs: 1 or 2]. A common ${p.cov==='CS'?'compound-symmetry':'first-order autoregressive, AR(1),'} covariance structure was assumed, with a correlation of ${p.rho} between ${p.cov==='CS'?'any two visits':'adjacent equally spaced visits'} [justify the covariance assumptions and report sensitivity analyses where evidence is limited]. `;}
else {const labels=p.kind==='casecontrol'?['病例组暴露比例','对照组暴露比例','exposure prevalence among cases','exposure prevalence among controls']:p.kind==='cohort'?['暴露组固定随访事件风险','未暴露组固定随访事件风险','fixed-horizon event risk in the exposed group','fixed-horizon event risk in the unexposed group']:['试验组主要结局事件发生率','对照组主要结局事件发生率','primary-outcome event rate in the experimental group','primary-outcome event rate in the control group'];zh=`预计${labels[0]}为${pct(p.pT)}，${labels[1]}为${pct(p.pC)} [填写事件/暴露定义和观察时点；参数来源：预实验、与本研究高度相关的文献，或自行开展的系统综述/Meta分析，引用1或2并说明选择理由]。${p.kind==='cohort'?`其中暴露组风险由对照风险与预期RR=${p.rr}推导。`:p.kind==='casecontrol'?`其中病例暴露比例由对照暴露比例与预期OR=${p.or}推导；采用非匹配设计。`:`预期绝对风险差（T−C）为${+(100*(p.pT-p.pC)).toFixed(4)}个百分点。`}`;en=`The anticipated ${labels[0]&&labels[2]} was ${pct(p.pT)}, compared with ${pct(p.pC)} for the ${labels[3]} [define the event/exposure and assessment time; justify assumptions using pilot data, closely related studies, or a de novo systematic review/meta-analysis; cite 1 or 2]. ${p.kind==='cohort'?`The exposed-group risk was derived using an anticipated RR of ${p.rr}. `:p.kind==='casecontrol'?`The exposure prevalence among cases was derived using an anticipated OR of ${p.or}; an unmatched design was assumed. `:`The expected absolute risk difference (T minus C) was ${+(100*(p.pT-p.pC)).toFixed(4)} percentage points. `}`;}
let testZh=p.objective==='interaction'?'总体Wald交互检验':'双侧差异检验',testEn=p.objective==='interaction'?'an omnibus Wald interaction test':'a two-sided test of between-group difference';
if(p.test==='noninferiority'){testZh='单侧非劣效检验';testEn='a one-sided non-inferiority test';zh+=`非劣效界值预先设为${p.margin}${p.kind==='binary'?`（风险差，即${pct(p.margin)}的绝对差）`:' [结局单位]'}，结局${p.direction==='lower'?'越低越好':'越高越好'} [补充界值的临床可接受性、历史对照疗效及保留效应依据，并添加对应参考文献；不能仅依据可招募人数选择界值]。`;en+=`The prespecified non-inferiority margin was ${p.margin}${p.kind==='binary'?' on the absolute risk-difference scale':' [outcome units]'}, with ${p.direction==='lower'?'lower':'higher'} outcome values indicating benefit [justify clinical acceptability, historical control effects and effect preservation, with relevant citations; do not choose the margin solely for recruitment feasibility]. `;}
if(p.test==='equivalence'){testZh='双单侧等效检验（TOST，每个单侧检验）';testEn='two one-sided tests of equivalence (TOST; alpha for each one-sided test)';zh+=`预设等效区间为−${p.margin}至+${p.margin} [填写单位；说明上下界的临床意义及文献依据]。`;en+=`The prespecified equivalence bounds were −${p.margin} and +${p.margin} [specify units and justify both bounds clinically, with references]. `;}
const methodZh=p.kind==='repeated'?'完整资料、已知协方差的Wald大样本近似':p.kind==='mean'?'两独立样本均值的正态近似':p.test==='superiority'?'零假设下采用合并比例方差、备择假设下采用组别比例方差的两比例正态近似':'采用预设比例所确定规划方差的风险差正态近似';const methodEn=p.kind==='repeated'?'a large-sample Wald approximation assuming complete data and known covariance':p.kind==='mean'?'a normal approximation for two independent means':p.test==='superiority'?'a two-proportion normal approximation using pooled variance under the null and group-specific variances under the alternative':'a normal approximation for the risk difference using planning variances from the assumed proportions';
zh+=`采用${testZh}，α=${p.alpha}，目标把握度为${pct(p.power)}，组T与组C的${c.design==='rct'?'随机分配':'样本量'}比为1:${p.ratio}。使用${methodZh}计算，至少需要组T ${r.nT}人、组C ${r.nC}人，总计${r.total}名可分析参与者。考虑${pct(p.dropout)}的失访或无效资料 [依据：4]，逐组以n/(1−失访率)向上取整，计划纳入组T ${r.recruitT}人、组C ${r.recruitC}人，共${r.recruitTotal}人。计算使用StatCannon独立教学引擎v${r.version} [补充可访问网址、使用日期和方法依据：3；如改用其他软件复核，应填写实际软件名称、版本、具体程序及重算结果，不得未经使用写成PASS]。`;
en+=`Using ${testEn}, alpha=${p.alpha}, ${pct(p.power)} power and a ${c.design==='rct'?'randomization':'sample-size'} ratio of 1:${p.ratio} (T:C), ${methodEn} yielded a requirement of ${r.nT} analyzable participants in group T and ${r.nC} in group C (${r.total} in total). Allowing for ${pct(p.dropout)} attrition or unusable data [source: 4], each group size was divided by (1−attrition) and rounded up, giving recruitment targets of ${r.recruitT} and ${r.recruitC}, respectively (${r.recruitTotal} in total). Calculations were performed with the independent StatCannon teaching engine v${r.version} [provide its URL, access date and methodological reference: 3; if independently recalculated in other software, report the actual software, version, procedure and revised results rather than claiming use of PASS without having used it]. `;
if(p.kind==='repeated'){zh+='本规划未包含部分访视缺失、协方差估计不确定性、基线校正或小样本自由度修正，球形性ε未用于样本量调整 [按最终MMRM分析模型和缺失机制进行进一步模拟/复核，并报告方法与结果]。';en+='This planning approximation did not incorporate intermittent missingness, uncertainty in covariance estimation, baseline adjustment or small-sample degrees-of-freedom corrections; no sphericity-epsilon adjustment was applied [further validate against the planned MMRM and missing-data mechanism, and report the methods and findings]. ';}
return{zh:'【中文稿：基于教学参数生成；替换所有方括号内容并核实假设后用于方案。当前为计划招募表述，论文应按实际设计与实施情况修订。】\n'+zh+refsZh,en:'[English draft based on teaching assumptions: replace all bracketed placeholders and verify assumptions before use. Recruitment targets describe the plan; adapt the manuscript wording to the study actually conducted.]\n'+en+refsEn};}
window.PassReport={create};
})();
