(function(){'use strict';
const C=window.PassContent,M=window.PassMath,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected='rm-average',design='rct',outcome='repeated',raw={},verified=false,result=null;
const current=()=>C.cases.find(c=>c.id===selected);
function field(k){const [label,type,hint]=C.fieldMeta[k];return `<div class="pass-field"><label for="pass-${k}">${label}</label><button type="button" class="pass-help" data-help="${k}" aria-label="${label}教学说明">?</button>${type==='select'?`<select id="pass-${k}" name="${k}"><option value="">请根据案例判断</option>${hint.split('|').map(x=>{const [v,t]=x.split(':');return `<option value="${v}" ${raw[k]===v?'selected':''}>${t}</option>`}).join('')}</select>`:`<input id="pass-${k}" name="${k}" type="text" inputmode="${type==='number'?'decimal':'text'}" value="${esc(raw[k]||'')}" autocomplete="off" aria-describedby="error-${k}"><small>${hint}</small>`}<div class="pass-error" id="error-${k}"></div></div>`;}
function shell(){const c=current(),src=C.sources[c.source];return `<section id="pass-workspace"><header class="pass-head"><span>研究设计 → 参数判断 → 计算 → 迁移</span><h1>PASS 样本量大炮</h1><p>案例驱动的样本量教学工作台 · 独立教学工具，非 PASS 官方软件</p></header><div class="pass-selectors"><label>研究设计<select id="pass-design"><option value="rct" ${design==='rct'?'selected':''}>随机对照试验 RCT</option><option value="observational" ${design==='observational'?'selected':''}>观察性研究</option></select></label><label>结局类型<select id="pass-outcome">${[['continuous','连续结局'],['binary','二分类结局'],...(design==='rct'?[['repeated','连续结局重复测量']]:[])].map(([v,t])=>`<option value="${v}" ${v===outcome?'selected':''}>${t}</option>`).join('')}</select></label><label>具体场景<select id="pass-case">${C.cases.filter(x=>x.design===design&&x.outcome===outcome).map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${x.title}</option>`).join('')}</select></label></div><article class="pass-box"><h2>01 · 读案例，先明确研究问题</h2><h3>${c.title}</h3><p>${c.story}</p><details><summary>案例来源与教学假设</summary><p>${src.fact} 本练习借用真实研究背景，所有数值及迁移设计均为独立教学假设，不复现原论文的样本量方案。</p><a href="${src.url}" target="_blank" rel="noopener">${src.name}</a></details></article><form id="pass-form" class="pass-box" novalidate><h2>02 · 自己填写参数</h2><p>比例填写小数；多个数值用逗号分隔。每个“？”包含填写方法、理由、原理和易错点。这里校验的是本案例预先给定的假设，不代表真实研究只有唯一合法参数。</p><div class="pass-fields">${c.fields.map(field).join('')}</div><div class="pass-actions"><button type="submit">检查我的判断</button><button type="button" id="pass-calculate" disabled>通过检查后计算</button><button type="button" id="pass-reset">重新练习</button></div><p id="pass-status" role="status" aria-live="polite">关键参数全部正确后解锁计算。</p></form><div id="pass-result" aria-live="polite"></div><article class="pass-box"><h2>参考方法与边界</h2><p>本版为透明公式教学近似，未与商业 PASS 数值逐项对照。两组均值采用正态近似；比例优效采用合并零假设方差；非劣效/等效采用固定规划方差的正态近似，非 Farrington–Manning 或精确法。重复测量采用已知协方差、完整资料的 Wald 规划近似，不能替代含缺失机制、协方差估计及小样本自由度修正的 MMRM 模拟。</p>${C.docs.map(x=>`<p><a href="${x.url}" target="_blank" rel="noopener">${x.name}</a></p>`).join('')}</article><dialog id="pass-dialog"><button type="button" id="pass-close">关闭 ×</button><div id="pass-help-content"></div></dialog></section>`;}
function parse(c){const p={kind:c.kind},errors=[];c.fields.forEach(k=>{const v=(raw[k]||'').trim(),type=C.fieldMeta[k][1];let x=type==='number'?Number(v):type==='array'?v.split(/[,，\s]+/).map(Number):v;const e=c.expected[k];let same=Array.isArray(e)?Array.isArray(x)&&x.length===e.length&&x.every((n,i)=>Number.isFinite(n)&&Math.abs(n-e[i])<1e-7):typeof e==='number'?Number.isFinite(x)&&Math.abs(x-e)<1e-7:x===e;if(!v||!same)errors.push(k);p[k]=x;});return{p,errors};}
function methods(c,r){const p=r.p,params=c.fields.map(k=>`${C.fieldMeta[k][0]}=${Array.isArray(p[k])?p[k].join(', '):p[k]}`).join('；');return `【教学方案描述模板：正式方案需依据先验文献及主要分析计划复核】\n采用统计学大炮独立教学引擎 v${M.version} 进行样本量近似规划（并非调用 PASS 软件）。研究情境：${c.title}。参数：${params}。显著性水平按${p.test==='superiority'?'双侧检验（交互为总体Wald检验）':p.test==='equivalence'?'TOST每个单侧检验':'单侧检验'}定义。计算得到可分析组T ${r.nT}人、组C ${r.nC}人，共${r.total}人；分别按 ceil(n/(1−失访率)) 调整后计划招募组T ${r.recruitT}人、组C ${r.recruitC}人，总计${r.recruitTotal}人。整数样本量下近似功效为${(r.achieved*100).toFixed(2)}%。${p.kind==='repeated'?'重复测量使用两组共同的预设协方差矩阵及完整资料Wald近似；ε不参与检验。未模拟部分访视缺失，未采用Kenward–Roger/Satterthwaite修正或基线校正，不能宣称等同最终MMRM的精确功效。':'使用正态大样本规划近似，未采用小样本t、精确检验或非劣效比例的约束评分法。'}所有数值为本教学案例假设，正式方案应补充效应量、方差及界值的证据来源。`;}
function trajectory(p){const values=[...p.muT,...p.muC],low=Math.min(...values)-2,high=Math.max(...values)+2,x=i=>55+i*470/(p.m-1),y=v=>170-(v-low)/(high-low)*140;return `<figure class="pass-trajectory"><figcaption>预期均值轨迹（教学假设） · 蓝色：组T，橙色：组C</figcaption><svg viewBox="0 0 580 215" role="img" aria-label="两组教学均值轨迹，数值见参数表">${[low,high].map(v=>`<text x="8" y="${y(v)+4}" fill="#315774">${v}</text><path d="M45 ${y(v)} H540" stroke="#d8e5ee"/>`).join('')}${[['muT','#127cbb'],['muC','#c67729']].map(([k,color])=>`<polyline fill="none" stroke="${color}" stroke-width="3" points="${p[k].map((v,i)=>x(i)+','+y(v)).join(' ')}"/>${p[k].map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="${color}"/><text x="${x(i)}" y="${y(v)-8}" fill="${color}" text-anchor="middle">${v}</text>`).join('')}`).join('')}${p.months.map((m,i)=>`<text x="${x(i)}" y="200" text-anchor="middle" fill="#315774">${m}月</text>`).join('')}</svg></figure>`;}
function renderResult(root){const c=current(),r=result,p=r.p;root.querySelector('#pass-result').innerHTML=`<article class="pass-box pass-success"><h2>03 · 计算结果与方法说明</h2><p>教学近似结果 · 组T=${p.kind==='casecontrol'?'病例':'试验 / 暴露'}，组C=${p.kind==='casecontrol'?'对照':'对照 / 非暴露'}</p><table><thead><tr><th>样本量</th><th>组T</th><th>组C</th><th>总计</th></tr></thead><tbody><tr><th>失访调整前</th><td>${r.nT}</td><td>${r.nC}</td><td>${r.total}</td></tr><tr><th>计划招募</th><td>${r.recruitT}</td><td>${r.recruitC}</td><td><strong>${r.recruitTotal}</strong></td></tr></tbody></table><p>目标功效 ${(p.power*100).toFixed(0)}% · 整数样本量下近似功效 ${(r.achieved*100).toFixed(2)}%。${r.nT<30||r.nC<30?' 样本量较小，正态/Wald近似可能不充分，应进行小样本方法或模拟复核。':''}</p>${p.kind==='repeated'?`${trajectory(p)}<h3>协方差矩阵 Σ（结局单位的平方）</h3><div class="pass-scroll"><table>${r.sigma.map(row=>`<tr>${row.map(x=>`<td>${x.toFixed(1)}</td>`).join('')}</tr>`).join('')}</table></div><p>从协方差导出的球形性诊断 ε≈${r.eps.toFixed(3)}，本 Wald 计算不使用它修正样本量。${p.objective==='interaction'?'检验组间差异随时间变化，采用非中心χ²联合功效。':'使用预设访视对比 c，方差为 c′Σc × (1/nT+1/nC)。'}</p><details><summary>探索：同一组轨迹，不同目标与协方差结构</summary><p>下表改变研究问题或先验假设，只用于比较；不能按最小人数选择主要终点。所有结果均为失访调整后的总人数。</p><table><tr><th>目标</th><th>CS</th><th>AR(1)</th></tr>${[['endpoint','6个月'],['average','四次平均'],['interaction','时间交互']].map(([o,t])=>`<tr><th>${t}</th>${['CS','AR1'].map(cov=>`<td>${M.solve({...p,objective:o,cov}).recruitTotal}</td>`).join('')}</tr>`).join('')}</table></details>`:''}<h3>技术计算记录</h3><textarea aria-label="样本量计算描述模板" id="pass-methods" rows="10" readonly>${esc(methods(c,r))}</textarea><button id="pass-copy" type="button">复制描述</button><h3>中文论文／研究方案表述</h3><textarea aria-label="中文论文样本量描述" id="pass-zh" rows="14" readonly>${esc(window.PassReport.create(c,r).zh)}</textarea><button type="button" id="copy-zh">复制中文</button><h3>English manuscript / protocol wording</h3><textarea aria-label="英文论文样本量描述" id="pass-en" rows="14" readonly>${esc(window.PassReport.create(c,r).en)}</textarea><button type="button" id="copy-en">Copy English</button><button id="pass-download" type="button">下载计算记录</button><h3>04 · 回到知识，再迁移到真实研究</h3><p>解释：哪个参数最依赖临床证据？若主要结局或分析方法改变，哪些假设需要重新论证？</p><textarea aria-label="我的学习反思" id="pass-reflection" rows="3" placeholder="写下你的判断（可选；下载记录时一并保存）"></textarea><p><a data-route="textbook" href="textbook/">回到教材查证</a> · <a data-route="datasets" href="datasets/">进入 D01–D07 数据实战</a></p><p>已通过的案例仅保存在当前浏览器；练习参数不是患者数据。</p></article>`;
 root.querySelector('#pass-copy').onclick=async()=>{const area=root.querySelector('#pass-methods');try{await navigator.clipboard.writeText(area.value);root.querySelector('#pass-copy').textContent='已复制';}catch(e){area.select();root.querySelector('#pass-copy').textContent='请复制已选中文字';}};
 for(const lang of ['zh','en'])root.querySelector('#copy-'+lang).onclick=async()=>{const a=root.querySelector('#pass-'+lang),b=root.querySelector('#copy-'+lang);try{await navigator.clipboard.writeText(a.value);b.textContent=lang==='zh'?'已复制':'Copied';}catch(e){a.select();b.textContent=lang==='zh'?'请复制已选文字':'Copy the selected text';}};
 root.querySelector('#pass-download').onclick=()=>{const blob=new Blob([JSON.stringify({case:c.title,parameters:p,result:r,methods:methods(c,r),manuscript:window.PassReport.create(c,r),reflection:root.querySelector('#pass-reflection').value,date:new Date().toISOString()},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`PASS教学记录-${c.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
 try{const key='statcannon_pass_v1',data=JSON.parse(localStorage.getItem(key)||'{}');data[c.id]={date:new Date().toISOString(),total:r.recruitTotal};localStorage.setItem(key,JSON.stringify(data));}catch(e){}
}
function mount(root){const box=root.querySelector('#pass-workspace');const redraw=()=>{root.querySelector('#pass-workspace').outerHTML=shell();mount(root);};function change(){raw={};verified=false;result=null;redraw();}
 box.querySelector('#pass-design').onchange=e=>{design=e.target.value;if(design==='observational'&&outcome==='repeated')outcome='continuous';selected=C.cases.find(c=>c.design===design&&c.outcome===outcome).id;change();};box.querySelector('#pass-outcome').onchange=e=>{outcome=e.target.value;selected=C.cases.find(c=>c.design===design&&c.outcome===outcome).id;change();};box.querySelector('#pass-case').onchange=e=>{selected=e.target.value;change();};box.querySelector('#pass-reset').onclick=change;
 const form=box.querySelector('#pass-form');form.oninput=e=>{if(!e.target.name)return;raw[e.target.name]=e.target.value;verified=false;result=null;box.querySelector('#pass-calculate').disabled=true;box.querySelector('#pass-result').innerHTML='';box.querySelector('#pass-status').textContent='参数已修改，请重新检查。';};form.onchange=form.oninput;
 form.onsubmit=e=>{e.preventDefault();const v=parse(current());for(const k of current().fields){const bad=v.errors.includes(k);box.querySelector('#pass-'+k).setAttribute('aria-invalid',String(bad));box.querySelector('#error-'+k).textContent=bad?'这里需要重新判断：'+({alpha:'核对单侧/双侧约定及百分数的小数转换。',power:'区分把握度1−β和β，并检查百分数转换。',ratio:'确认哪组在分母，按组C人数除以组T人数。',dropout:'核对受试者失访比例，不是每次访视缺失比例。',delta:'按组T减组C，保留符号，不能填写组内变化。',sdT:'核对组T的个体标准差，不是标准误。',sdC:'核对组C的个体标准差，不是标准误。',pT:'核对组T的事件定义与概率单位。',pC:'确认题目要的是对照事件风险还是暴露比例。',rr:'风险比是风险相除，不是风险相减。',or:'优势比与风险比不能互换。',margin:'核对可接受劣势/等效边界及原单位；风险差用小数。',direction:'根据结局判断越高还是越低越好。',test:'重新阅读要证明差异、不劣还是等效。',objective:'确认问题是末次、平均差异还是时间交互。',m:'只计算题目纳入分析的治疗后访视。',months:'按先后顺序输入每个纳入访视的月份。',muT:'依次核对试验组各访视均值及顺序。',muC:'依次核对对照组各访视均值及顺序。',sd:'每次访视需要一个边际标准差。',cov:'检查相关是否随时间间隔增加而衰减。',rho:'核对同一受试者测量间的相关假设。',epsilon:'区分单变量RM-ANOVA与本题Wald/MMRM规划。'}[k]||'核对案例定义。'):'';}verified=!v.errors.length;box.querySelector('#pass-calculate').disabled=!verified;box.querySelector('#pass-status').textContent=verified?'全部关键参数判断正确，可以计算。':`还有 ${v.errors.length} 项需要重新判断；点击该参数旁的“？”查阅原理。`;};
 box.querySelector('#pass-calculate').onclick=()=>{if(!verified)return;try{result=M.solve(parse(current()).p);renderResult(box);}catch(e){box.querySelector('#pass-status').textContent=e.message;}};
 box.querySelectorAll('[data-help]').forEach(b=>b.onclick=()=>{const k=b.dataset.help;box.querySelector('#pass-help-content').innerHTML=`<h2>${C.fieldMeta[k][0]}</h2>${C.help[k].map((t,i)=>`<h3>${['这里应该填什么','为什么填这个','统计学原理','临床研究者常见错误'][i]}</h3><p>${t}</p>`).join('')}`;box.querySelector('#pass-dialog').showModal();});box.querySelector('#pass-close').onclick=()=>box.querySelector('#pass-dialog').close();box.querySelector('#pass-calculate').disabled=!verified;if(result&&verified){box.querySelector('#pass-calculate').disabled=false;renderResult(box);}
}
window.PassUI={shell,mount,parse};
})();
